# Historic data

In [28]:
import sys
import os
import pandas as pd
project_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
sys.path.append(project_root)
print(project_root)

c:\Users\marco\OneDrive\Escritorio\Mis_proyectitos\electricity-price-forecast

In [29]:
# Importing scrappers
from src.scraper import download_omie_price
from src.scraper import download_omie_range_v2

In [41]:
from datetime import datetime
today = datetime.today().strftime("%Y%m%d")
print(today)

20260428

In [43]:
#df_historic = download_omie_range_v2("20000101", today)
# THERE ARE NO HISTORICAL DATA!!!

In [46]:
# Here installation of OMIE data from 2020
#!pip install OMIEData

In [47]:
import datetime as dt
from OMIEData.DataImport.omie_marginalprice_importer import OMIEMarginalPriceFileImporter

dateIni = dt.datetime(2019, 1, 1)
dateEnd = dt.datetime(2024, 12, 31)

df_historic = OMIEMarginalPriceFileImporter(
    date_ini=dateIni, 
    date_end=dateEnd
).read_to_dataframe(verbose=True)

print(df_historic.shape)
print(df_historic.head())

Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_01_01_2019_01_01_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\DataImport\omie_data_importer_from_responses.py:29: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df = pd.concat([df, self.fileReader.get_data_from_response(response=response)], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_01_01_2019_01_01_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_02_01_2019_02_01_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_02_01_2019_02_01_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_03_01_2019_03_01_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_03_01_2019_03_01_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_04_01_2019_04_01_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_04_01_2019_04_01_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_05_01_2019_05_01_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_05_01_2019_05_01_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_06_01_2019_06_01_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_06_01_2019_06_01_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_07_01_2019_07_01_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_07_01_2019_07_01_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_08_01_2019_08_01_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_08_01_2019_08_01_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_09_01_2019_09_01_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_09_01_2019_09_01_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_10_01_2019_10_01_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_10_01_2019_10_01_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_11_01_2019_11_01_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_11_01_2019_11_01_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_12_01_2019_12_01_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_12_01_2019_12_01_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_13_01_2019_13_01_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_13_01_2019_13_01_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_14_01_2019_14_01_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_14_01_2019_14_01_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_15_01_2019_15_01_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_15_01_2019_15_01_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_16_01_2019_16_01_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_16_01_2019_16_01_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_17_01_2019_17_01_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_17_01_2019_17_01_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_18_01_2019_18_01_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_18_01_2019_18_01_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_19_01_2019_19_01_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_19_01_2019_19_01_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_20_01_2019_20_01_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_20_01_2019_20_01_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_21_01_2019_21_01_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_21_01_2019_21_01_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_22_01_2019_22_01_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_22_01_2019_22_01_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_23_01_2019_23_01_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_23_01_2019_23_01_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_24_01_2019_24_01_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_24_01_2019_24_01_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_25_01_2019_25_01_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_25_01_2019_25_01_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_26_01_2019_26_01_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_26_01_2019_26_01_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_27_01_2019_27_01_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_27_01_2019_27_01_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_28_01_2019_28_01_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_28_01_2019_28_01_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_29_01_2019_29_01_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_29_01_2019_29_01_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_30_01_2019_30_01_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_30_01_2019_30_01_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_31_01_2019_31_01_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_01/TXT/INT_PBC_EV_H_1_31_01_2019_31_01_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_01_02_2019_01_02_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_01_02_2019_01_02_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_02_02_2019_02_02_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_02_02_2019_02_02_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_03_02_2019_03_02_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_03_02_2019_03_02_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_04_02_2019_04_02_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_04_02_2019_04_02_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_05_02_2019_05_02_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_05_02_2019_05_02_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_06_02_2019_06_02_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_06_02_2019_06_02_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_07_02_2019_07_02_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_07_02_2019_07_02_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_08_02_2019_08_02_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_08_02_2019_08_02_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_09_02_2019_09_02_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_09_02_2019_09_02_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_10_02_2019_10_02_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_10_02_2019_10_02_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_11_02_2019_11_02_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_11_02_2019_11_02_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_12_02_2019_12_02_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_12_02_2019_12_02_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_13_02_2019_13_02_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_13_02_2019_13_02_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_14_02_2019_14_02_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_14_02_2019_14_02_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_15_02_2019_15_02_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_15_02_2019_15_02_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_16_02_2019_16_02_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_16_02_2019_16_02_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_17_02_2019_17_02_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_17_02_2019_17_02_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_18_02_2019_18_02_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_18_02_2019_18_02_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_19_02_2019_19_02_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_19_02_2019_19_02_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_20_02_2019_20_02_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_20_02_2019_20_02_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_21_02_2019_21_02_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_21_02_2019_21_02_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_22_02_2019_22_02_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_22_02_2019_22_02_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_23_02_2019_23_02_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_23_02_2019_23_02_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_24_02_2019_24_02_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_24_02_2019_24_02_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_25_02_2019_25_02_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_25_02_2019_25_02_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_26_02_2019_26_02_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_26_02_2019_26_02_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_27_02_2019_27_02_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_27_02_2019_27_02_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_28_02_2019_28_02_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_02/TXT/INT_PBC_EV_H_1_28_02_2019_28_02_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_01_03_2019_01_03_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_01_03_2019_01_03_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_02_03_2019_02_03_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_02_03_2019_02_03_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_03_03_2019_03_03_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_03_03_2019_03_03_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_04_03_2019_04_03_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_04_03_2019_04_03_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_05_03_2019_05_03_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_05_03_2019_05_03_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_06_03_2019_06_03_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_06_03_2019_06_03_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_07_03_2019_07_03_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_07_03_2019_07_03_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_08_03_2019_08_03_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_08_03_2019_08_03_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_09_03_2019_09_03_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_09_03_2019_09_03_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_10_03_2019_10_03_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_10_03_2019_10_03_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_11_03_2019_11_03_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_11_03_2019_11_03_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_12_03_2019_12_03_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_12_03_2019_12_03_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_13_03_2019_13_03_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_13_03_2019_13_03_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_14_03_2019_14_03_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_14_03_2019_14_03_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_15_03_2019_15_03_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_15_03_2019_15_03_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_16_03_2019_16_03_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_16_03_2019_16_03_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_17_03_2019_17_03_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_17_03_2019_17_03_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_18_03_2019_18_03_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_18_03_2019_18_03_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_19_03_2019_19_03_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_19_03_2019_19_03_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_20_03_2019_20_03_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_20_03_2019_20_03_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_21_03_2019_21_03_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_21_03_2019_21_03_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_22_03_2019_22_03_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_22_03_2019_22_03_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_23_03_2019_23_03_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_23_03_2019_23_03_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_24_03_2019_24_03_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_24_03_2019_24_03_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_25_03_2019_25_03_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_25_03_2019_25_03_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_26_03_2019_26_03_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_26_03_2019_26_03_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_27_03_2019_27_03_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_27_03_2019_27_03_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_28_03_2019_28_03_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_28_03_2019_28_03_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_29_03_2019_29_03_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_29_03_2019_29_03_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_30_03_2019_30_03_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_30_03_2019_30_03_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_31_03_2019_31_03_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_03/TXT/INT_PBC_EV_H_1_31_03_2019_31_03_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_01_04_2019_01_04_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_01_04_2019_01_04_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_02_04_2019_02_04_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_02_04_2019_02_04_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_03_04_2019_03_04_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_03_04_2019_03_04_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_04_04_2019_04_04_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_04_04_2019_04_04_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_05_04_2019_05_04_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_05_04_2019_05_04_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_06_04_2019_06_04_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_06_04_2019_06_04_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_07_04_2019_07_04_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_07_04_2019_07_04_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_08_04_2019_08_04_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_08_04_2019_08_04_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_09_04_2019_09_04_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_09_04_2019_09_04_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_10_04_2019_10_04_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_10_04_2019_10_04_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_11_04_2019_11_04_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_11_04_2019_11_04_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_12_04_2019_12_04_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_12_04_2019_12_04_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_13_04_2019_13_04_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_13_04_2019_13_04_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_14_04_2019_14_04_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_14_04_2019_14_04_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_15_04_2019_15_04_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_15_04_2019_15_04_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_16_04_2019_16_04_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_16_04_2019_16_04_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_17_04_2019_17_04_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_17_04_2019_17_04_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_18_04_2019_18_04_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_18_04_2019_18_04_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_19_04_2019_19_04_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_19_04_2019_19_04_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_20_04_2019_20_04_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_20_04_2019_20_04_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_21_04_2019_21_04_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_21_04_2019_21_04_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_22_04_2019_22_04_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_22_04_2019_22_04_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_23_04_2019_23_04_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_23_04_2019_23_04_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_24_04_2019_24_04_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_24_04_2019_24_04_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_25_04_2019_25_04_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_25_04_2019_25_04_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_26_04_2019_26_04_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_26_04_2019_26_04_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_27_04_2019_27_04_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_27_04_2019_27_04_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_28_04_2019_28_04_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_28_04_2019_28_04_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_29_04_2019_29_04_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_29_04_2019_29_04_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_30_04_2019_30_04_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_04/TXT/INT_PBC_EV_H_1_30_04_2019_30_04_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_01_05_2019_01_05_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_01_05_2019_01_05_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_02_05_2019_02_05_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_02_05_2019_02_05_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_03_05_2019_03_05_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_03_05_2019_03_05_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_04_05_2019_04_05_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_04_05_2019_04_05_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_05_05_2019_05_05_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_05_05_2019_05_05_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_06_05_2019_06_05_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_06_05_2019_06_05_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_07_05_2019_07_05_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_07_05_2019_07_05_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_08_05_2019_08_05_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_08_05_2019_08_05_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_09_05_2019_09_05_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_09_05_2019_09_05_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_10_05_2019_10_05_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_10_05_2019_10_05_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_11_05_2019_11_05_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_11_05_2019_11_05_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_12_05_2019_12_05_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_12_05_2019_12_05_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_13_05_2019_13_05_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_13_05_2019_13_05_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_14_05_2019_14_05_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_14_05_2019_14_05_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_15_05_2019_15_05_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_15_05_2019_15_05_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_16_05_2019_16_05_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_16_05_2019_16_05_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_17_05_2019_17_05_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_17_05_2019_17_05_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_18_05_2019_18_05_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_18_05_2019_18_05_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_19_05_2019_19_05_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_19_05_2019_19_05_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_20_05_2019_20_05_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_20_05_2019_20_05_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_21_05_2019_21_05_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_21_05_2019_21_05_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_22_05_2019_22_05_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_22_05_2019_22_05_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_23_05_2019_23_05_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_23_05_2019_23_05_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_24_05_2019_24_05_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_24_05_2019_24_05_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_25_05_2019_25_05_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_25_05_2019_25_05_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_26_05_2019_26_05_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_26_05_2019_26_05_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_27_05_2019_27_05_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_27_05_2019_27_05_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_28_05_2019_28_05_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_28_05_2019_28_05_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_29_05_2019_29_05_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_29_05_2019_29_05_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_30_05_2019_30_05_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_30_05_2019_30_05_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_31_05_2019_31_05_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_05/TXT/INT_PBC_EV_H_1_31_05_2019_31_05_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_01_06_2019_01_06_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_01_06_2019_01_06_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_02_06_2019_02_06_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_02_06_2019_02_06_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_03_06_2019_03_06_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_03_06_2019_03_06_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_04_06_2019_04_06_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_04_06_2019_04_06_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_05_06_2019_05_06_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_05_06_2019_05_06_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_06_06_2019_06_06_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_06_06_2019_06_06_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_07_06_2019_07_06_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_07_06_2019_07_06_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_08_06_2019_08_06_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_08_06_2019_08_06_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_09_06_2019_09_06_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_09_06_2019_09_06_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_10_06_2019_10_06_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_10_06_2019_10_06_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_11_06_2019_11_06_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_11_06_2019_11_06_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_12_06_2019_12_06_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_12_06_2019_12_06_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_13_06_2019_13_06_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_13_06_2019_13_06_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_14_06_2019_14_06_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_14_06_2019_14_06_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_15_06_2019_15_06_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_15_06_2019_15_06_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_16_06_2019_16_06_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_16_06_2019_16_06_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_17_06_2019_17_06_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_17_06_2019_17_06_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_18_06_2019_18_06_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_18_06_2019_18_06_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_19_06_2019_19_06_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_19_06_2019_19_06_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_20_06_2019_20_06_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_20_06_2019_20_06_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_21_06_2019_21_06_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_21_06_2019_21_06_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_22_06_2019_22_06_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_22_06_2019_22_06_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_23_06_2019_23_06_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_23_06_2019_23_06_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_24_06_2019_24_06_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_24_06_2019_24_06_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_25_06_2019_25_06_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_25_06_2019_25_06_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_26_06_2019_26_06_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_26_06_2019_26_06_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_27_06_2019_27_06_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_27_06_2019_27_06_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_28_06_2019_28_06_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_28_06_2019_28_06_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_29_06_2019_29_06_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_29_06_2019_29_06_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_30_06_2019_30_06_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_06/TXT/INT_PBC_EV_H_1_30_06_2019_30_06_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_01_07_2019_01_07_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_01_07_2019_01_07_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_02_07_2019_02_07_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_02_07_2019_02_07_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_03_07_2019_03_07_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_03_07_2019_03_07_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_04_07_2019_04_07_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_04_07_2019_04_07_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_05_07_2019_05_07_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_05_07_2019_05_07_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_06_07_2019_06_07_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_06_07_2019_06_07_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_07_07_2019_07_07_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_07_07_2019_07_07_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_08_07_2019_08_07_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_08_07_2019_08_07_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_09_07_2019_09_07_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_09_07_2019_09_07_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_10_07_2019_10_07_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_10_07_2019_10_07_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_11_07_2019_11_07_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_11_07_2019_11_07_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_12_07_2019_12_07_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_12_07_2019_12_07_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_13_07_2019_13_07_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_13_07_2019_13_07_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_14_07_2019_14_07_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_14_07_2019_14_07_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_15_07_2019_15_07_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_15_07_2019_15_07_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_16_07_2019_16_07_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_16_07_2019_16_07_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_17_07_2019_17_07_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_17_07_2019_17_07_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_18_07_2019_18_07_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_18_07_2019_18_07_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_19_07_2019_19_07_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_19_07_2019_19_07_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_20_07_2019_20_07_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_20_07_2019_20_07_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_21_07_2019_21_07_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_21_07_2019_21_07_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_22_07_2019_22_07_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_22_07_2019_22_07_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_23_07_2019_23_07_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_23_07_2019_23_07_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_24_07_2019_24_07_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_24_07_2019_24_07_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_25_07_2019_25_07_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_25_07_2019_25_07_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_26_07_2019_26_07_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_26_07_2019_26_07_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_27_07_2019_27_07_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_27_07_2019_27_07_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_28_07_2019_28_07_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_28_07_2019_28_07_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_29_07_2019_29_07_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_29_07_2019_29_07_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_30_07_2019_30_07_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_30_07_2019_30_07_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_31_07_2019_31_07_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_07/TXT/INT_PBC_EV_H_1_31_07_2019_31_07_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_01_08_2019_01_08_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_01_08_2019_01_08_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_02_08_2019_02_08_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_02_08_2019_02_08_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_03_08_2019_03_08_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_03_08_2019_03_08_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_04_08_2019_04_08_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_04_08_2019_04_08_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_05_08_2019_05_08_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_05_08_2019_05_08_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_06_08_2019_06_08_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_06_08_2019_06_08_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_07_08_2019_07_08_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_07_08_2019_07_08_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_08_08_2019_08_08_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_08_08_2019_08_08_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_09_08_2019_09_08_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_09_08_2019_09_08_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_10_08_2019_10_08_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_10_08_2019_10_08_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_11_08_2019_11_08_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_11_08_2019_11_08_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_12_08_2019_12_08_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_12_08_2019_12_08_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_13_08_2019_13_08_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_13_08_2019_13_08_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_14_08_2019_14_08_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_14_08_2019_14_08_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_15_08_2019_15_08_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_15_08_2019_15_08_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_16_08_2019_16_08_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_16_08_2019_16_08_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_17_08_2019_17_08_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_17_08_2019_17_08_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_18_08_2019_18_08_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_18_08_2019_18_08_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_19_08_2019_19_08_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_19_08_2019_19_08_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_20_08_2019_20_08_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_20_08_2019_20_08_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_21_08_2019_21_08_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_21_08_2019_21_08_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_22_08_2019_22_08_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_22_08_2019_22_08_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_23_08_2019_23_08_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_23_08_2019_23_08_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_24_08_2019_24_08_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_24_08_2019_24_08_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_25_08_2019_25_08_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_25_08_2019_25_08_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_26_08_2019_26_08_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_26_08_2019_26_08_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_27_08_2019_27_08_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_27_08_2019_27_08_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_28_08_2019_28_08_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_28_08_2019_28_08_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_29_08_2019_29_08_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_29_08_2019_29_08_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_30_08_2019_30_08_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_30_08_2019_30_08_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_31_08_2019_31_08_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_08/TXT/INT_PBC_EV_H_1_31_08_2019_31_08_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_01_09_2019_01_09_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_01_09_2019_01_09_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_02_09_2019_02_09_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_02_09_2019_02_09_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_03_09_2019_03_09_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_03_09_2019_03_09_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_04_09_2019_04_09_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_04_09_2019_04_09_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_05_09_2019_05_09_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_05_09_2019_05_09_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_06_09_2019_06_09_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_06_09_2019_06_09_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_07_09_2019_07_09_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_07_09_2019_07_09_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_08_09_2019_08_09_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_08_09_2019_08_09_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_09_09_2019_09_09_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_09_09_2019_09_09_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_10_09_2019_10_09_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_10_09_2019_10_09_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_11_09_2019_11_09_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_11_09_2019_11_09_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_12_09_2019_12_09_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_12_09_2019_12_09_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_13_09_2019_13_09_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_13_09_2019_13_09_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_14_09_2019_14_09_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_14_09_2019_14_09_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_15_09_2019_15_09_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_15_09_2019_15_09_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_16_09_2019_16_09_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_16_09_2019_16_09_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_17_09_2019_17_09_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_17_09_2019_17_09_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_18_09_2019_18_09_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_18_09_2019_18_09_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_19_09_2019_19_09_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_19_09_2019_19_09_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_20_09_2019_20_09_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_20_09_2019_20_09_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_21_09_2019_21_09_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_21_09_2019_21_09_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_22_09_2019_22_09_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_22_09_2019_22_09_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_23_09_2019_23_09_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_23_09_2019_23_09_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_24_09_2019_24_09_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_24_09_2019_24_09_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_25_09_2019_25_09_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_25_09_2019_25_09_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_26_09_2019_26_09_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_26_09_2019_26_09_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_27_09_2019_27_09_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_27_09_2019_27_09_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_28_09_2019_28_09_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_28_09_2019_28_09_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_29_09_2019_29_09_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_29_09_2019_29_09_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_30_09_2019_30_09_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_09/TXT/INT_PBC_EV_H_1_30_09_2019_30_09_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_01_10_2019_01_10_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_01_10_2019_01_10_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_02_10_2019_02_10_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_02_10_2019_02_10_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_03_10_2019_03_10_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_03_10_2019_03_10_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_04_10_2019_04_10_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_04_10_2019_04_10_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_05_10_2019_05_10_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_05_10_2019_05_10_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_06_10_2019_06_10_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_06_10_2019_06_10_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_07_10_2019_07_10_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_07_10_2019_07_10_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_08_10_2019_08_10_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_08_10_2019_08_10_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_09_10_2019_09_10_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_09_10_2019_09_10_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_10_10_2019_10_10_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_10_10_2019_10_10_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_11_10_2019_11_10_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_11_10_2019_11_10_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_12_10_2019_12_10_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_12_10_2019_12_10_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_13_10_2019_13_10_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_13_10_2019_13_10_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_14_10_2019_14_10_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_14_10_2019_14_10_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_15_10_2019_15_10_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_15_10_2019_15_10_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_16_10_2019_16_10_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_16_10_2019_16_10_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_17_10_2019_17_10_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_17_10_2019_17_10_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_18_10_2019_18_10_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_18_10_2019_18_10_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_19_10_2019_19_10_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_19_10_2019_19_10_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_20_10_2019_20_10_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_20_10_2019_20_10_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_21_10_2019_21_10_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_21_10_2019_21_10_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_22_10_2019_22_10_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_22_10_2019_22_10_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_23_10_2019_23_10_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_23_10_2019_23_10_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_24_10_2019_24_10_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_24_10_2019_24_10_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_25_10_2019_25_10_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_25_10_2019_25_10_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_26_10_2019_26_10_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_26_10_2019_26_10_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_27_10_2019_27_10_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_27_10_2019_27_10_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_28_10_2019_28_10_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_28_10_2019_28_10_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_29_10_2019_29_10_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_29_10_2019_29_10_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_30_10_2019_30_10_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_30_10_2019_30_10_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_31_10_2019_31_10_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_10/TXT/INT_PBC_EV_H_1_31_10_2019_31_10_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_01_11_2019_01_11_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_01_11_2019_01_11_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_02_11_2019_02_11_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_02_11_2019_02_11_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_03_11_2019_03_11_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_03_11_2019_03_11_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_04_11_2019_04_11_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_04_11_2019_04_11_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_05_11_2019_05_11_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_05_11_2019_05_11_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_06_11_2019_06_11_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_06_11_2019_06_11_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_07_11_2019_07_11_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_07_11_2019_07_11_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_08_11_2019_08_11_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_08_11_2019_08_11_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_09_11_2019_09_11_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_09_11_2019_09_11_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_10_11_2019_10_11_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_10_11_2019_10_11_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_11_11_2019_11_11_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_11_11_2019_11_11_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_12_11_2019_12_11_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_12_11_2019_12_11_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_13_11_2019_13_11_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_13_11_2019_13_11_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_14_11_2019_14_11_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_14_11_2019_14_11_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_15_11_2019_15_11_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_15_11_2019_15_11_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_16_11_2019_16_11_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_16_11_2019_16_11_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_17_11_2019_17_11_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_17_11_2019_17_11_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_18_11_2019_18_11_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_18_11_2019_18_11_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_19_11_2019_19_11_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_19_11_2019_19_11_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_20_11_2019_20_11_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_20_11_2019_20_11_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_21_11_2019_21_11_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_21_11_2019_21_11_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_22_11_2019_22_11_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_22_11_2019_22_11_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_23_11_2019_23_11_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_23_11_2019_23_11_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_24_11_2019_24_11_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_24_11_2019_24_11_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_25_11_2019_25_11_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_25_11_2019_25_11_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_26_11_2019_26_11_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_26_11_2019_26_11_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_27_11_2019_27_11_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_27_11_2019_27_11_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_28_11_2019_28_11_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_28_11_2019_28_11_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_29_11_2019_29_11_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_29_11_2019_29_11_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_30_11_2019_30_11_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_11/TXT/INT_PBC_EV_H_1_30_11_2019_30_11_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_01_12_2019_01_12_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_01_12_2019_01_12_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_02_12_2019_02_12_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_02_12_2019_02_12_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_03_12_2019_03_12_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_03_12_2019_03_12_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_04_12_2019_04_12_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_04_12_2019_04_12_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_05_12_2019_05_12_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_05_12_2019_05_12_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_06_12_2019_06_12_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_06_12_2019_06_12_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_07_12_2019_07_12_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_07_12_2019_07_12_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_08_12_2019_08_12_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_08_12_2019_08_12_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_09_12_2019_09_12_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_09_12_2019_09_12_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_10_12_2019_10_12_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_10_12_2019_10_12_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_11_12_2019_11_12_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_11_12_2019_11_12_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_12_12_2019_12_12_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_12_12_2019_12_12_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_13_12_2019_13_12_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_13_12_2019_13_12_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_14_12_2019_14_12_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_14_12_2019_14_12_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_15_12_2019_15_12_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_15_12_2019_15_12_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_16_12_2019_16_12_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_16_12_2019_16_12_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_17_12_2019_17_12_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_17_12_2019_17_12_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_18_12_2019_18_12_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_18_12_2019_18_12_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_19_12_2019_19_12_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_19_12_2019_19_12_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_20_12_2019_20_12_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_20_12_2019_20_12_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_21_12_2019_21_12_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_21_12_2019_21_12_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_22_12_2019_22_12_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_22_12_2019_22_12_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_23_12_2019_23_12_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_23_12_2019_23_12_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_24_12_2019_24_12_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_24_12_2019_24_12_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_25_12_2019_25_12_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_25_12_2019_25_12_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_26_12_2019_26_12_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_26_12_2019_26_12_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_27_12_2019_27_12_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_27_12_2019_27_12_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_28_12_2019_28_12_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_28_12_2019_28_12_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_29_12_2019_29_12_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_29_12_2019_29_12_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_30_12_2019_30_12_2019.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_30_12_2019_30_12_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_31_12_2019_31_12_2019.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2019/MES_12/TXT/INT_PBC_EV_H_1_31_12_2019_31_12_2019.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_01_01_2020_01_01_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_01_01_2020_01_01_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_02_01_2020_02_01_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_02_01_2020_02_01_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_03_01_2020_03_01_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_03_01_2020_03_01_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_04_01_2020_04_01_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_04_01_2020_04_01_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_05_01_2020_05_01_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_05_01_2020_05_01_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_06_01_2020_06_01_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_06_01_2020_06_01_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_07_01_2020_07_01_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_07_01_2020_07_01_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_08_01_2020_08_01_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_08_01_2020_08_01_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_09_01_2020_09_01_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_09_01_2020_09_01_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_10_01_2020_10_01_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_10_01_2020_10_01_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_11_01_2020_11_01_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_11_01_2020_11_01_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_12_01_2020_12_01_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_12_01_2020_12_01_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_13_01_2020_13_01_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_13_01_2020_13_01_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_14_01_2020_14_01_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_14_01_2020_14_01_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_15_01_2020_15_01_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_15_01_2020_15_01_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_16_01_2020_16_01_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_16_01_2020_16_01_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_17_01_2020_17_01_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_17_01_2020_17_01_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_18_01_2020_18_01_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_18_01_2020_18_01_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_19_01_2020_19_01_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_19_01_2020_19_01_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_20_01_2020_20_01_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_20_01_2020_20_01_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_21_01_2020_21_01_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_21_01_2020_21_01_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_22_01_2020_22_01_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_22_01_2020_22_01_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_23_01_2020_23_01_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_23_01_2020_23_01_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_24_01_2020_24_01_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_24_01_2020_24_01_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_25_01_2020_25_01_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_25_01_2020_25_01_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_26_01_2020_26_01_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_26_01_2020_26_01_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_27_01_2020_27_01_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_27_01_2020_27_01_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_28_01_2020_28_01_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_28_01_2020_28_01_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_29_01_2020_29_01_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_29_01_2020_29_01_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_30_01_2020_30_01_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_30_01_2020_30_01_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_31_01_2020_31_01_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_01/TXT/INT_PBC_EV_H_1_31_01_2020_31_01_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_01_02_2020_01_02_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_01_02_2020_01_02_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_02_02_2020_02_02_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_02_02_2020_02_02_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_03_02_2020_03_02_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_03_02_2020_03_02_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_04_02_2020_04_02_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_04_02_2020_04_02_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_05_02_2020_05_02_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_05_02_2020_05_02_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_06_02_2020_06_02_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_06_02_2020_06_02_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_07_02_2020_07_02_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_07_02_2020_07_02_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_08_02_2020_08_02_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_08_02_2020_08_02_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_09_02_2020_09_02_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_09_02_2020_09_02_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_10_02_2020_10_02_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_10_02_2020_10_02_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_11_02_2020_11_02_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_11_02_2020_11_02_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_12_02_2020_12_02_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_12_02_2020_12_02_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_13_02_2020_13_02_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_13_02_2020_13_02_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_14_02_2020_14_02_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_14_02_2020_14_02_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_15_02_2020_15_02_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_15_02_2020_15_02_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_16_02_2020_16_02_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_16_02_2020_16_02_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_17_02_2020_17_02_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_17_02_2020_17_02_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_18_02_2020_18_02_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_18_02_2020_18_02_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_19_02_2020_19_02_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_19_02_2020_19_02_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_20_02_2020_20_02_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_20_02_2020_20_02_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_21_02_2020_21_02_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_21_02_2020_21_02_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_22_02_2020_22_02_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_22_02_2020_22_02_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_23_02_2020_23_02_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_23_02_2020_23_02_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_24_02_2020_24_02_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_24_02_2020_24_02_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_25_02_2020_25_02_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_25_02_2020_25_02_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_26_02_2020_26_02_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_26_02_2020_26_02_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_27_02_2020_27_02_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_27_02_2020_27_02_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_28_02_2020_28_02_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_28_02_2020_28_02_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_29_02_2020_29_02_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_02/TXT/INT_PBC_EV_H_1_29_02_2020_29_02_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_01_03_2020_01_03_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_01_03_2020_01_03_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_02_03_2020_02_03_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_02_03_2020_02_03_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_03_03_2020_03_03_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_03_03_2020_03_03_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_04_03_2020_04_03_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_04_03_2020_04_03_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_05_03_2020_05_03_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_05_03_2020_05_03_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_06_03_2020_06_03_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_06_03_2020_06_03_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_07_03_2020_07_03_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_07_03_2020_07_03_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_08_03_2020_08_03_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_08_03_2020_08_03_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_09_03_2020_09_03_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_09_03_2020_09_03_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_10_03_2020_10_03_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_10_03_2020_10_03_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_11_03_2020_11_03_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_11_03_2020_11_03_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_12_03_2020_12_03_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_12_03_2020_12_03_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_13_03_2020_13_03_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_13_03_2020_13_03_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_14_03_2020_14_03_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_14_03_2020_14_03_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_15_03_2020_15_03_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_15_03_2020_15_03_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_16_03_2020_16_03_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_16_03_2020_16_03_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_17_03_2020_17_03_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_17_03_2020_17_03_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_18_03_2020_18_03_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_18_03_2020_18_03_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_19_03_2020_19_03_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_19_03_2020_19_03_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_20_03_2020_20_03_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_20_03_2020_20_03_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_21_03_2020_21_03_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_21_03_2020_21_03_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_22_03_2020_22_03_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_22_03_2020_22_03_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_23_03_2020_23_03_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_23_03_2020_23_03_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_24_03_2020_24_03_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_24_03_2020_24_03_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_25_03_2020_25_03_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_25_03_2020_25_03_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_26_03_2020_26_03_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_26_03_2020_26_03_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_27_03_2020_27_03_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_27_03_2020_27_03_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_28_03_2020_28_03_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_28_03_2020_28_03_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_29_03_2020_29_03_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_29_03_2020_29_03_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_30_03_2020_30_03_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_30_03_2020_30_03_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_31_03_2020_31_03_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_03/TXT/INT_PBC_EV_H_1_31_03_2020_31_03_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_01_04_2020_01_04_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_01_04_2020_01_04_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_02_04_2020_02_04_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_02_04_2020_02_04_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_03_04_2020_03_04_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_03_04_2020_03_04_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_04_04_2020_04_04_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_04_04_2020_04_04_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_05_04_2020_05_04_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_05_04_2020_05_04_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_06_04_2020_06_04_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_06_04_2020_06_04_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_07_04_2020_07_04_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_07_04_2020_07_04_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_08_04_2020_08_04_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_08_04_2020_08_04_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_09_04_2020_09_04_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_09_04_2020_09_04_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_10_04_2020_10_04_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_10_04_2020_10_04_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_11_04_2020_11_04_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_11_04_2020_11_04_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_12_04_2020_12_04_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_12_04_2020_12_04_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_13_04_2020_13_04_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_13_04_2020_13_04_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_14_04_2020_14_04_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_14_04_2020_14_04_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_15_04_2020_15_04_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_15_04_2020_15_04_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_16_04_2020_16_04_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_16_04_2020_16_04_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_17_04_2020_17_04_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_17_04_2020_17_04_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_18_04_2020_18_04_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_18_04_2020_18_04_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_19_04_2020_19_04_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_19_04_2020_19_04_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_20_04_2020_20_04_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_20_04_2020_20_04_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_21_04_2020_21_04_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_21_04_2020_21_04_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_22_04_2020_22_04_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_22_04_2020_22_04_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_23_04_2020_23_04_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_23_04_2020_23_04_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_24_04_2020_24_04_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_24_04_2020_24_04_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_25_04_2020_25_04_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_25_04_2020_25_04_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_26_04_2020_26_04_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_26_04_2020_26_04_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_27_04_2020_27_04_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_27_04_2020_27_04_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_28_04_2020_28_04_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_28_04_2020_28_04_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_29_04_2020_29_04_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_29_04_2020_29_04_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_30_04_2020_30_04_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_04/TXT/INT_PBC_EV_H_1_30_04_2020_30_04_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_01_05_2020_01_05_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_01_05_2020_01_05_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_02_05_2020_02_05_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_02_05_2020_02_05_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_03_05_2020_03_05_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_03_05_2020_03_05_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_04_05_2020_04_05_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_04_05_2020_04_05_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_05_05_2020_05_05_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_05_05_2020_05_05_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_06_05_2020_06_05_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_06_05_2020_06_05_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_07_05_2020_07_05_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_07_05_2020_07_05_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_08_05_2020_08_05_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_08_05_2020_08_05_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_09_05_2020_09_05_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_09_05_2020_09_05_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_10_05_2020_10_05_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_10_05_2020_10_05_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_11_05_2020_11_05_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_11_05_2020_11_05_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_12_05_2020_12_05_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_12_05_2020_12_05_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_13_05_2020_13_05_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_13_05_2020_13_05_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_14_05_2020_14_05_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_14_05_2020_14_05_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_15_05_2020_15_05_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_15_05_2020_15_05_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_16_05_2020_16_05_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_16_05_2020_16_05_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_17_05_2020_17_05_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_17_05_2020_17_05_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_18_05_2020_18_05_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_18_05_2020_18_05_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_19_05_2020_19_05_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_19_05_2020_19_05_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_20_05_2020_20_05_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_20_05_2020_20_05_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_21_05_2020_21_05_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_21_05_2020_21_05_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_22_05_2020_22_05_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_22_05_2020_22_05_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_23_05_2020_23_05_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_23_05_2020_23_05_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_24_05_2020_24_05_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_24_05_2020_24_05_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_25_05_2020_25_05_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_25_05_2020_25_05_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_26_05_2020_26_05_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_26_05_2020_26_05_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_27_05_2020_27_05_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_27_05_2020_27_05_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_28_05_2020_28_05_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_28_05_2020_28_05_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_29_05_2020_29_05_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_29_05_2020_29_05_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_30_05_2020_30_05_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_30_05_2020_30_05_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_31_05_2020_31_05_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_05/TXT/INT_PBC_EV_H_1_31_05_2020_31_05_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_01_06_2020_01_06_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_01_06_2020_01_06_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_02_06_2020_02_06_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_02_06_2020_02_06_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_03_06_2020_03_06_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_03_06_2020_03_06_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_04_06_2020_04_06_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_04_06_2020_04_06_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_05_06_2020_05_06_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_05_06_2020_05_06_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_06_06_2020_06_06_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_06_06_2020_06_06_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_07_06_2020_07_06_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_07_06_2020_07_06_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_08_06_2020_08_06_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_08_06_2020_08_06_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_09_06_2020_09_06_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_09_06_2020_09_06_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_10_06_2020_10_06_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_10_06_2020_10_06_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_11_06_2020_11_06_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_11_06_2020_11_06_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_12_06_2020_12_06_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_12_06_2020_12_06_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_13_06_2020_13_06_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_13_06_2020_13_06_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_14_06_2020_14_06_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_14_06_2020_14_06_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_15_06_2020_15_06_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_15_06_2020_15_06_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_16_06_2020_16_06_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_16_06_2020_16_06_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_17_06_2020_17_06_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_17_06_2020_17_06_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_18_06_2020_18_06_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_18_06_2020_18_06_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_19_06_2020_19_06_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_19_06_2020_19_06_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_20_06_2020_20_06_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_20_06_2020_20_06_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_21_06_2020_21_06_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_21_06_2020_21_06_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_22_06_2020_22_06_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_22_06_2020_22_06_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_23_06_2020_23_06_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_23_06_2020_23_06_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_24_06_2020_24_06_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_24_06_2020_24_06_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_25_06_2020_25_06_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_25_06_2020_25_06_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_26_06_2020_26_06_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_26_06_2020_26_06_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_27_06_2020_27_06_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_27_06_2020_27_06_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_28_06_2020_28_06_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_28_06_2020_28_06_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_29_06_2020_29_06_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_29_06_2020_29_06_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_30_06_2020_30_06_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_06/TXT/INT_PBC_EV_H_1_30_06_2020_30_06_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_01_07_2020_01_07_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_01_07_2020_01_07_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_02_07_2020_02_07_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_02_07_2020_02_07_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_03_07_2020_03_07_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_03_07_2020_03_07_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_04_07_2020_04_07_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_04_07_2020_04_07_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_05_07_2020_05_07_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_05_07_2020_05_07_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_06_07_2020_06_07_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_06_07_2020_06_07_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_07_07_2020_07_07_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_07_07_2020_07_07_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_08_07_2020_08_07_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_08_07_2020_08_07_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_09_07_2020_09_07_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_09_07_2020_09_07_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_10_07_2020_10_07_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_10_07_2020_10_07_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_11_07_2020_11_07_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_11_07_2020_11_07_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_12_07_2020_12_07_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_12_07_2020_12_07_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_13_07_2020_13_07_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_13_07_2020_13_07_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_14_07_2020_14_07_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_14_07_2020_14_07_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_15_07_2020_15_07_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_15_07_2020_15_07_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_16_07_2020_16_07_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_16_07_2020_16_07_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_17_07_2020_17_07_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_17_07_2020_17_07_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_18_07_2020_18_07_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_18_07_2020_18_07_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_19_07_2020_19_07_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_19_07_2020_19_07_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_20_07_2020_20_07_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_20_07_2020_20_07_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_21_07_2020_21_07_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_21_07_2020_21_07_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_22_07_2020_22_07_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_22_07_2020_22_07_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_23_07_2020_23_07_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_23_07_2020_23_07_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_24_07_2020_24_07_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_24_07_2020_24_07_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_25_07_2020_25_07_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_25_07_2020_25_07_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_26_07_2020_26_07_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_26_07_2020_26_07_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_27_07_2020_27_07_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_27_07_2020_27_07_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_28_07_2020_28_07_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_28_07_2020_28_07_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_29_07_2020_29_07_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_29_07_2020_29_07_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_30_07_2020_30_07_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_30_07_2020_30_07_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_31_07_2020_31_07_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_07/TXT/INT_PBC_EV_H_1_31_07_2020_31_07_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_01_08_2020_01_08_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_01_08_2020_01_08_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_02_08_2020_02_08_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_02_08_2020_02_08_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_03_08_2020_03_08_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_03_08_2020_03_08_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_04_08_2020_04_08_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_04_08_2020_04_08_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_05_08_2020_05_08_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_05_08_2020_05_08_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_06_08_2020_06_08_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_06_08_2020_06_08_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_07_08_2020_07_08_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_07_08_2020_07_08_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_08_08_2020_08_08_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_08_08_2020_08_08_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_09_08_2020_09_08_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_09_08_2020_09_08_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_10_08_2020_10_08_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_10_08_2020_10_08_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_11_08_2020_11_08_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_11_08_2020_11_08_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_12_08_2020_12_08_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_12_08_2020_12_08_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_13_08_2020_13_08_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_13_08_2020_13_08_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_14_08_2020_14_08_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_14_08_2020_14_08_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_15_08_2020_15_08_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_15_08_2020_15_08_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_16_08_2020_16_08_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_16_08_2020_16_08_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_17_08_2020_17_08_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_17_08_2020_17_08_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_18_08_2020_18_08_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_18_08_2020_18_08_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_19_08_2020_19_08_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_19_08_2020_19_08_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_20_08_2020_20_08_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_20_08_2020_20_08_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_21_08_2020_21_08_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_21_08_2020_21_08_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_22_08_2020_22_08_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_22_08_2020_22_08_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_23_08_2020_23_08_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_23_08_2020_23_08_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_24_08_2020_24_08_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_24_08_2020_24_08_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_25_08_2020_25_08_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_25_08_2020_25_08_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_26_08_2020_26_08_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_26_08_2020_26_08_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_27_08_2020_27_08_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_27_08_2020_27_08_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_28_08_2020_28_08_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_28_08_2020_28_08_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_29_08_2020_29_08_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_29_08_2020_29_08_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_30_08_2020_30_08_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_30_08_2020_30_08_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_31_08_2020_31_08_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_08/TXT/INT_PBC_EV_H_1_31_08_2020_31_08_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_01_09_2020_01_09_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_01_09_2020_01_09_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_02_09_2020_02_09_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_02_09_2020_02_09_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_03_09_2020_03_09_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_03_09_2020_03_09_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_04_09_2020_04_09_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_04_09_2020_04_09_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_05_09_2020_05_09_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_05_09_2020_05_09_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_06_09_2020_06_09_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_06_09_2020_06_09_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_07_09_2020_07_09_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_07_09_2020_07_09_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_08_09_2020_08_09_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_08_09_2020_08_09_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_09_09_2020_09_09_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_09_09_2020_09_09_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_10_09_2020_10_09_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_10_09_2020_10_09_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_11_09_2020_11_09_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_11_09_2020_11_09_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_12_09_2020_12_09_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_12_09_2020_12_09_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_13_09_2020_13_09_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_13_09_2020_13_09_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_14_09_2020_14_09_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_14_09_2020_14_09_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_15_09_2020_15_09_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_15_09_2020_15_09_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_16_09_2020_16_09_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_16_09_2020_16_09_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_17_09_2020_17_09_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_17_09_2020_17_09_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_18_09_2020_18_09_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_18_09_2020_18_09_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_19_09_2020_19_09_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_19_09_2020_19_09_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_20_09_2020_20_09_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_20_09_2020_20_09_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_21_09_2020_21_09_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_21_09_2020_21_09_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_22_09_2020_22_09_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_22_09_2020_22_09_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_23_09_2020_23_09_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_23_09_2020_23_09_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_24_09_2020_24_09_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_24_09_2020_24_09_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_25_09_2020_25_09_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_25_09_2020_25_09_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_26_09_2020_26_09_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_26_09_2020_26_09_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_27_09_2020_27_09_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_27_09_2020_27_09_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_28_09_2020_28_09_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_28_09_2020_28_09_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_29_09_2020_29_09_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_29_09_2020_29_09_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_30_09_2020_30_09_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_09/TXT/INT_PBC_EV_H_1_30_09_2020_30_09_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_01_10_2020_01_10_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_01_10_2020_01_10_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_02_10_2020_02_10_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_02_10_2020_02_10_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_03_10_2020_03_10_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_03_10_2020_03_10_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_04_10_2020_04_10_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_04_10_2020_04_10_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_05_10_2020_05_10_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_05_10_2020_05_10_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_06_10_2020_06_10_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_06_10_2020_06_10_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_07_10_2020_07_10_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_07_10_2020_07_10_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_08_10_2020_08_10_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_08_10_2020_08_10_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_09_10_2020_09_10_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_09_10_2020_09_10_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_10_10_2020_10_10_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_10_10_2020_10_10_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_11_10_2020_11_10_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_11_10_2020_11_10_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_12_10_2020_12_10_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_12_10_2020_12_10_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_13_10_2020_13_10_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_13_10_2020_13_10_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_14_10_2020_14_10_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_14_10_2020_14_10_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_15_10_2020_15_10_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_15_10_2020_15_10_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_16_10_2020_16_10_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_16_10_2020_16_10_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_17_10_2020_17_10_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_17_10_2020_17_10_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_18_10_2020_18_10_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_18_10_2020_18_10_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_19_10_2020_19_10_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_19_10_2020_19_10_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_20_10_2020_20_10_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_20_10_2020_20_10_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_21_10_2020_21_10_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_21_10_2020_21_10_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_22_10_2020_22_10_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_22_10_2020_22_10_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_23_10_2020_23_10_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_23_10_2020_23_10_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_24_10_2020_24_10_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_24_10_2020_24_10_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_25_10_2020_25_10_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_25_10_2020_25_10_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_26_10_2020_26_10_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_26_10_2020_26_10_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_27_10_2020_27_10_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_27_10_2020_27_10_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_28_10_2020_28_10_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_28_10_2020_28_10_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_29_10_2020_29_10_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_29_10_2020_29_10_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_30_10_2020_30_10_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_30_10_2020_30_10_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_31_10_2020_31_10_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_10/TXT/INT_PBC_EV_H_1_31_10_2020_31_10_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_01_11_2020_01_11_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_01_11_2020_01_11_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_02_11_2020_02_11_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_02_11_2020_02_11_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_03_11_2020_03_11_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_03_11_2020_03_11_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_04_11_2020_04_11_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_04_11_2020_04_11_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_05_11_2020_05_11_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_05_11_2020_05_11_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_06_11_2020_06_11_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_06_11_2020_06_11_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_07_11_2020_07_11_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_07_11_2020_07_11_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_08_11_2020_08_11_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_08_11_2020_08_11_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_09_11_2020_09_11_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_09_11_2020_09_11_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_10_11_2020_10_11_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_10_11_2020_10_11_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_11_11_2020_11_11_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_11_11_2020_11_11_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_12_11_2020_12_11_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_12_11_2020_12_11_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_13_11_2020_13_11_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_13_11_2020_13_11_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_14_11_2020_14_11_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_14_11_2020_14_11_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_15_11_2020_15_11_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_15_11_2020_15_11_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_16_11_2020_16_11_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_16_11_2020_16_11_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_17_11_2020_17_11_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_17_11_2020_17_11_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_18_11_2020_18_11_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_18_11_2020_18_11_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_19_11_2020_19_11_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_19_11_2020_19_11_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_20_11_2020_20_11_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_20_11_2020_20_11_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_21_11_2020_21_11_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_21_11_2020_21_11_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_22_11_2020_22_11_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_22_11_2020_22_11_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_23_11_2020_23_11_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_23_11_2020_23_11_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_24_11_2020_24_11_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_24_11_2020_24_11_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_25_11_2020_25_11_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_25_11_2020_25_11_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_26_11_2020_26_11_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_26_11_2020_26_11_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_27_11_2020_27_11_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_27_11_2020_27_11_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_28_11_2020_28_11_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_28_11_2020_28_11_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_29_11_2020_29_11_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_29_11_2020_29_11_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_30_11_2020_30_11_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_11/TXT/INT_PBC_EV_H_1_30_11_2020_30_11_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_01_12_2020_01_12_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_01_12_2020_01_12_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_02_12_2020_02_12_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_02_12_2020_02_12_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_03_12_2020_03_12_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_03_12_2020_03_12_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_04_12_2020_04_12_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_04_12_2020_04_12_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_05_12_2020_05_12_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_05_12_2020_05_12_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_06_12_2020_06_12_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_06_12_2020_06_12_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_07_12_2020_07_12_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_07_12_2020_07_12_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_08_12_2020_08_12_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_08_12_2020_08_12_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_09_12_2020_09_12_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_09_12_2020_09_12_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_10_12_2020_10_12_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_10_12_2020_10_12_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_11_12_2020_11_12_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_11_12_2020_11_12_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_12_12_2020_12_12_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_12_12_2020_12_12_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_13_12_2020_13_12_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_13_12_2020_13_12_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_14_12_2020_14_12_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_14_12_2020_14_12_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_15_12_2020_15_12_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_15_12_2020_15_12_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_16_12_2020_16_12_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_16_12_2020_16_12_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_17_12_2020_17_12_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_17_12_2020_17_12_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_18_12_2020_18_12_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_18_12_2020_18_12_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_19_12_2020_19_12_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_19_12_2020_19_12_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_20_12_2020_20_12_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_20_12_2020_20_12_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_21_12_2020_21_12_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_21_12_2020_21_12_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_22_12_2020_22_12_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_22_12_2020_22_12_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_23_12_2020_23_12_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_23_12_2020_23_12_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_24_12_2020_24_12_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_24_12_2020_24_12_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_25_12_2020_25_12_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_25_12_2020_25_12_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_26_12_2020_26_12_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_26_12_2020_26_12_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_27_12_2020_27_12_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_27_12_2020_27_12_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_28_12_2020_28_12_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_28_12_2020_28_12_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_29_12_2020_29_12_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_29_12_2020_29_12_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_30_12_2020_30_12_2020.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_30_12_2020_30_12_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_31_12_2020_31_12_2020.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2020/MES_12/TXT/INT_PBC_EV_H_1_31_12_2020_31_12_2020.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_01_01_2021_01_01_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_01_01_2021_01_01_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_02_01_2021_02_01_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_02_01_2021_02_01_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_03_01_2021_03_01_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_03_01_2021_03_01_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_04_01_2021_04_01_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_04_01_2021_04_01_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_05_01_2021_05_01_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_05_01_2021_05_01_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_06_01_2021_06_01_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_06_01_2021_06_01_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_07_01_2021_07_01_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_07_01_2021_07_01_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_08_01_2021_08_01_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_08_01_2021_08_01_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_09_01_2021_09_01_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_09_01_2021_09_01_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_10_01_2021_10_01_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_10_01_2021_10_01_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_11_01_2021_11_01_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_11_01_2021_11_01_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_12_01_2021_12_01_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_12_01_2021_12_01_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_13_01_2021_13_01_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_13_01_2021_13_01_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_14_01_2021_14_01_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_14_01_2021_14_01_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_15_01_2021_15_01_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_15_01_2021_15_01_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_16_01_2021_16_01_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_16_01_2021_16_01_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_17_01_2021_17_01_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_17_01_2021_17_01_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_18_01_2021_18_01_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_18_01_2021_18_01_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_19_01_2021_19_01_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_19_01_2021_19_01_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_20_01_2021_20_01_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_20_01_2021_20_01_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_21_01_2021_21_01_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_21_01_2021_21_01_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_22_01_2021_22_01_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_22_01_2021_22_01_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_23_01_2021_23_01_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_23_01_2021_23_01_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_24_01_2021_24_01_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_24_01_2021_24_01_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_25_01_2021_25_01_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_25_01_2021_25_01_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_26_01_2021_26_01_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_26_01_2021_26_01_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_27_01_2021_27_01_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_27_01_2021_27_01_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_28_01_2021_28_01_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_28_01_2021_28_01_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_29_01_2021_29_01_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_29_01_2021_29_01_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_30_01_2021_30_01_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_30_01_2021_30_01_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_31_01_2021_31_01_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_01/TXT/INT_PBC_EV_H_1_31_01_2021_31_01_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_01_02_2021_01_02_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_01_02_2021_01_02_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_02_02_2021_02_02_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_02_02_2021_02_02_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_03_02_2021_03_02_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_03_02_2021_03_02_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_04_02_2021_04_02_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_04_02_2021_04_02_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_05_02_2021_05_02_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_05_02_2021_05_02_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_06_02_2021_06_02_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_06_02_2021_06_02_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_07_02_2021_07_02_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_07_02_2021_07_02_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_08_02_2021_08_02_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_08_02_2021_08_02_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_09_02_2021_09_02_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_09_02_2021_09_02_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_10_02_2021_10_02_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_10_02_2021_10_02_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_11_02_2021_11_02_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_11_02_2021_11_02_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_12_02_2021_12_02_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_12_02_2021_12_02_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_13_02_2021_13_02_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_13_02_2021_13_02_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_14_02_2021_14_02_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_14_02_2021_14_02_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_15_02_2021_15_02_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_15_02_2021_15_02_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_16_02_2021_16_02_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_16_02_2021_16_02_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_17_02_2021_17_02_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_17_02_2021_17_02_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_18_02_2021_18_02_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_18_02_2021_18_02_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_19_02_2021_19_02_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_19_02_2021_19_02_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_20_02_2021_20_02_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_20_02_2021_20_02_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_21_02_2021_21_02_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_21_02_2021_21_02_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_22_02_2021_22_02_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_22_02_2021_22_02_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_23_02_2021_23_02_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_23_02_2021_23_02_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_24_02_2021_24_02_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_24_02_2021_24_02_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_25_02_2021_25_02_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_25_02_2021_25_02_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_26_02_2021_26_02_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_26_02_2021_26_02_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_27_02_2021_27_02_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_27_02_2021_27_02_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_28_02_2021_28_02_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_02/TXT/INT_PBC_EV_H_1_28_02_2021_28_02_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_01_03_2021_01_03_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_01_03_2021_01_03_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_02_03_2021_02_03_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_02_03_2021_02_03_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_03_03_2021_03_03_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_03_03_2021_03_03_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_04_03_2021_04_03_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_04_03_2021_04_03_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_05_03_2021_05_03_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_05_03_2021_05_03_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_06_03_2021_06_03_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_06_03_2021_06_03_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_07_03_2021_07_03_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_07_03_2021_07_03_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_08_03_2021_08_03_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_08_03_2021_08_03_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_09_03_2021_09_03_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_09_03_2021_09_03_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_10_03_2021_10_03_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_10_03_2021_10_03_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_11_03_2021_11_03_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_11_03_2021_11_03_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_12_03_2021_12_03_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_12_03_2021_12_03_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_13_03_2021_13_03_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_13_03_2021_13_03_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_14_03_2021_14_03_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_14_03_2021_14_03_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_15_03_2021_15_03_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_15_03_2021_15_03_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_16_03_2021_16_03_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_16_03_2021_16_03_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_17_03_2021_17_03_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_17_03_2021_17_03_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_18_03_2021_18_03_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_18_03_2021_18_03_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_19_03_2021_19_03_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_19_03_2021_19_03_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_20_03_2021_20_03_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_20_03_2021_20_03_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_21_03_2021_21_03_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_21_03_2021_21_03_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_22_03_2021_22_03_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_22_03_2021_22_03_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_23_03_2021_23_03_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_23_03_2021_23_03_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_24_03_2021_24_03_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_24_03_2021_24_03_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_25_03_2021_25_03_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_25_03_2021_25_03_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_26_03_2021_26_03_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_26_03_2021_26_03_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_27_03_2021_27_03_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_27_03_2021_27_03_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_28_03_2021_28_03_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_28_03_2021_28_03_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_29_03_2021_29_03_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_29_03_2021_29_03_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_30_03_2021_30_03_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_30_03_2021_30_03_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_31_03_2021_31_03_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_03/TXT/INT_PBC_EV_H_1_31_03_2021_31_03_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_01_04_2021_01_04_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_01_04_2021_01_04_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_02_04_2021_02_04_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_02_04_2021_02_04_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_03_04_2021_03_04_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_03_04_2021_03_04_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_04_04_2021_04_04_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_04_04_2021_04_04_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_05_04_2021_05_04_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_05_04_2021_05_04_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_06_04_2021_06_04_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_06_04_2021_06_04_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_07_04_2021_07_04_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_07_04_2021_07_04_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_08_04_2021_08_04_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_08_04_2021_08_04_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_09_04_2021_09_04_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_09_04_2021_09_04_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_10_04_2021_10_04_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_10_04_2021_10_04_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_11_04_2021_11_04_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_11_04_2021_11_04_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_12_04_2021_12_04_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_12_04_2021_12_04_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_13_04_2021_13_04_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_13_04_2021_13_04_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_14_04_2021_14_04_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_14_04_2021_14_04_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_15_04_2021_15_04_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_15_04_2021_15_04_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_16_04_2021_16_04_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_16_04_2021_16_04_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_17_04_2021_17_04_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_17_04_2021_17_04_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_18_04_2021_18_04_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_18_04_2021_18_04_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_19_04_2021_19_04_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_19_04_2021_19_04_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_20_04_2021_20_04_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_20_04_2021_20_04_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_21_04_2021_21_04_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_21_04_2021_21_04_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_22_04_2021_22_04_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_22_04_2021_22_04_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_23_04_2021_23_04_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_23_04_2021_23_04_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_24_04_2021_24_04_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_24_04_2021_24_04_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_25_04_2021_25_04_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_25_04_2021_25_04_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_26_04_2021_26_04_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_26_04_2021_26_04_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_27_04_2021_27_04_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_27_04_2021_27_04_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_28_04_2021_28_04_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_28_04_2021_28_04_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_29_04_2021_29_04_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_29_04_2021_29_04_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_30_04_2021_30_04_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_04/TXT/INT_PBC_EV_H_1_30_04_2021_30_04_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_01_05_2021_01_05_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_01_05_2021_01_05_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_02_05_2021_02_05_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_02_05_2021_02_05_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_03_05_2021_03_05_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_03_05_2021_03_05_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_04_05_2021_04_05_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_04_05_2021_04_05_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_05_05_2021_05_05_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_05_05_2021_05_05_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_06_05_2021_06_05_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_06_05_2021_06_05_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_07_05_2021_07_05_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_07_05_2021_07_05_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_08_05_2021_08_05_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_08_05_2021_08_05_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_09_05_2021_09_05_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_09_05_2021_09_05_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_10_05_2021_10_05_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_10_05_2021_10_05_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_11_05_2021_11_05_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_11_05_2021_11_05_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_12_05_2021_12_05_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_12_05_2021_12_05_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_13_05_2021_13_05_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_13_05_2021_13_05_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_14_05_2021_14_05_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_14_05_2021_14_05_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_15_05_2021_15_05_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_15_05_2021_15_05_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_16_05_2021_16_05_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_16_05_2021_16_05_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_17_05_2021_17_05_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_17_05_2021_17_05_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_18_05_2021_18_05_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_18_05_2021_18_05_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_19_05_2021_19_05_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_19_05_2021_19_05_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_20_05_2021_20_05_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_20_05_2021_20_05_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_21_05_2021_21_05_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_21_05_2021_21_05_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_22_05_2021_22_05_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_22_05_2021_22_05_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_23_05_2021_23_05_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_23_05_2021_23_05_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_24_05_2021_24_05_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_24_05_2021_24_05_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_25_05_2021_25_05_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_25_05_2021_25_05_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_26_05_2021_26_05_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_26_05_2021_26_05_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_27_05_2021_27_05_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_27_05_2021_27_05_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_28_05_2021_28_05_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_28_05_2021_28_05_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_29_05_2021_29_05_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_29_05_2021_29_05_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_30_05_2021_30_05_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_30_05_2021_30_05_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_31_05_2021_31_05_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_05/TXT/INT_PBC_EV_H_1_31_05_2021_31_05_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_01_06_2021_01_06_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_01_06_2021_01_06_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_02_06_2021_02_06_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_02_06_2021_02_06_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_03_06_2021_03_06_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_03_06_2021_03_06_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_04_06_2021_04_06_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_04_06_2021_04_06_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_05_06_2021_05_06_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_05_06_2021_05_06_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_06_06_2021_06_06_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_06_06_2021_06_06_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_07_06_2021_07_06_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_07_06_2021_07_06_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_08_06_2021_08_06_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_08_06_2021_08_06_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_09_06_2021_09_06_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_09_06_2021_09_06_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_10_06_2021_10_06_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_10_06_2021_10_06_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_11_06_2021_11_06_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_11_06_2021_11_06_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_12_06_2021_12_06_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_12_06_2021_12_06_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_13_06_2021_13_06_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_13_06_2021_13_06_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_14_06_2021_14_06_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_14_06_2021_14_06_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_15_06_2021_15_06_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_15_06_2021_15_06_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_16_06_2021_16_06_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_16_06_2021_16_06_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_17_06_2021_17_06_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_17_06_2021_17_06_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_18_06_2021_18_06_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_18_06_2021_18_06_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_19_06_2021_19_06_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_19_06_2021_19_06_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_20_06_2021_20_06_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_20_06_2021_20_06_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_21_06_2021_21_06_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_21_06_2021_21_06_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_22_06_2021_22_06_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_22_06_2021_22_06_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_23_06_2021_23_06_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_23_06_2021_23_06_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_24_06_2021_24_06_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_24_06_2021_24_06_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_25_06_2021_25_06_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_25_06_2021_25_06_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_26_06_2021_26_06_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_26_06_2021_26_06_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_27_06_2021_27_06_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_27_06_2021_27_06_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_28_06_2021_28_06_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_28_06_2021_28_06_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_29_06_2021_29_06_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_29_06_2021_29_06_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_30_06_2021_30_06_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_06/TXT/INT_PBC_EV_H_1_30_06_2021_30_06_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_01_07_2021_01_07_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_01_07_2021_01_07_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_02_07_2021_02_07_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_02_07_2021_02_07_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_03_07_2021_03_07_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_03_07_2021_03_07_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_04_07_2021_04_07_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_04_07_2021_04_07_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_05_07_2021_05_07_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_05_07_2021_05_07_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_06_07_2021_06_07_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_06_07_2021_06_07_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_07_07_2021_07_07_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_07_07_2021_07_07_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_08_07_2021_08_07_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_08_07_2021_08_07_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_09_07_2021_09_07_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_09_07_2021_09_07_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_10_07_2021_10_07_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_10_07_2021_10_07_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_11_07_2021_11_07_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_11_07_2021_11_07_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_12_07_2021_12_07_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_12_07_2021_12_07_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_13_07_2021_13_07_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_13_07_2021_13_07_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_14_07_2021_14_07_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_14_07_2021_14_07_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_15_07_2021_15_07_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_15_07_2021_15_07_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_16_07_2021_16_07_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_16_07_2021_16_07_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_17_07_2021_17_07_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_17_07_2021_17_07_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_18_07_2021_18_07_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_18_07_2021_18_07_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_19_07_2021_19_07_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_19_07_2021_19_07_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_20_07_2021_20_07_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_20_07_2021_20_07_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_21_07_2021_21_07_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_21_07_2021_21_07_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_22_07_2021_22_07_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_22_07_2021_22_07_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_23_07_2021_23_07_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_23_07_2021_23_07_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_24_07_2021_24_07_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_24_07_2021_24_07_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_25_07_2021_25_07_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_25_07_2021_25_07_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_26_07_2021_26_07_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_26_07_2021_26_07_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_27_07_2021_27_07_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_27_07_2021_27_07_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_28_07_2021_28_07_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_28_07_2021_28_07_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_29_07_2021_29_07_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_29_07_2021_29_07_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_30_07_2021_30_07_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_30_07_2021_30_07_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_31_07_2021_31_07_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_07/TXT/INT_PBC_EV_H_1_31_07_2021_31_07_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_01_08_2021_01_08_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_01_08_2021_01_08_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_02_08_2021_02_08_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_02_08_2021_02_08_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_03_08_2021_03_08_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_03_08_2021_03_08_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_04_08_2021_04_08_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_04_08_2021_04_08_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_05_08_2021_05_08_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_05_08_2021_05_08_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_06_08_2021_06_08_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_06_08_2021_06_08_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_07_08_2021_07_08_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_07_08_2021_07_08_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_08_08_2021_08_08_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_08_08_2021_08_08_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_09_08_2021_09_08_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_09_08_2021_09_08_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_10_08_2021_10_08_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_10_08_2021_10_08_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_11_08_2021_11_08_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_11_08_2021_11_08_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_12_08_2021_12_08_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_12_08_2021_12_08_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_13_08_2021_13_08_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_13_08_2021_13_08_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_14_08_2021_14_08_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_14_08_2021_14_08_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_15_08_2021_15_08_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_15_08_2021_15_08_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_16_08_2021_16_08_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_16_08_2021_16_08_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_17_08_2021_17_08_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_17_08_2021_17_08_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_18_08_2021_18_08_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_18_08_2021_18_08_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_19_08_2021_19_08_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_19_08_2021_19_08_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_20_08_2021_20_08_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_20_08_2021_20_08_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_21_08_2021_21_08_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_21_08_2021_21_08_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_22_08_2021_22_08_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_22_08_2021_22_08_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_23_08_2021_23_08_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_23_08_2021_23_08_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_24_08_2021_24_08_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_24_08_2021_24_08_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_25_08_2021_25_08_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_25_08_2021_25_08_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_26_08_2021_26_08_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_26_08_2021_26_08_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_27_08_2021_27_08_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_27_08_2021_27_08_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_28_08_2021_28_08_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_28_08_2021_28_08_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_29_08_2021_29_08_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_29_08_2021_29_08_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_30_08_2021_30_08_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_30_08_2021_30_08_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_31_08_2021_31_08_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_08/TXT/INT_PBC_EV_H_1_31_08_2021_31_08_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_01_09_2021_01_09_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_01_09_2021_01_09_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_02_09_2021_02_09_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_02_09_2021_02_09_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_03_09_2021_03_09_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_03_09_2021_03_09_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_04_09_2021_04_09_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_04_09_2021_04_09_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_05_09_2021_05_09_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_05_09_2021_05_09_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_06_09_2021_06_09_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_06_09_2021_06_09_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_07_09_2021_07_09_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_07_09_2021_07_09_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_08_09_2021_08_09_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_08_09_2021_08_09_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_09_09_2021_09_09_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_09_09_2021_09_09_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_10_09_2021_10_09_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_10_09_2021_10_09_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_11_09_2021_11_09_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_11_09_2021_11_09_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_12_09_2021_12_09_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_12_09_2021_12_09_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_13_09_2021_13_09_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_13_09_2021_13_09_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_14_09_2021_14_09_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_14_09_2021_14_09_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_15_09_2021_15_09_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_15_09_2021_15_09_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_16_09_2021_16_09_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_16_09_2021_16_09_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_17_09_2021_17_09_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_17_09_2021_17_09_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_18_09_2021_18_09_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_18_09_2021_18_09_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_19_09_2021_19_09_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_19_09_2021_19_09_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_20_09_2021_20_09_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_20_09_2021_20_09_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_21_09_2021_21_09_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_21_09_2021_21_09_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_22_09_2021_22_09_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_22_09_2021_22_09_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_23_09_2021_23_09_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_23_09_2021_23_09_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_24_09_2021_24_09_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_24_09_2021_24_09_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_25_09_2021_25_09_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_25_09_2021_25_09_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_26_09_2021_26_09_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_26_09_2021_26_09_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_27_09_2021_27_09_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_27_09_2021_27_09_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_28_09_2021_28_09_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_28_09_2021_28_09_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_29_09_2021_29_09_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_29_09_2021_29_09_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_30_09_2021_30_09_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_09/TXT/INT_PBC_EV_H_1_30_09_2021_30_09_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_01_10_2021_01_10_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_01_10_2021_01_10_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_02_10_2021_02_10_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_02_10_2021_02_10_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_03_10_2021_03_10_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_03_10_2021_03_10_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_04_10_2021_04_10_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_04_10_2021_04_10_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_05_10_2021_05_10_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_05_10_2021_05_10_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_06_10_2021_06_10_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_06_10_2021_06_10_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_07_10_2021_07_10_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_07_10_2021_07_10_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_08_10_2021_08_10_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_08_10_2021_08_10_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_09_10_2021_09_10_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_09_10_2021_09_10_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_10_10_2021_10_10_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_10_10_2021_10_10_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_11_10_2021_11_10_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_11_10_2021_11_10_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_12_10_2021_12_10_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_12_10_2021_12_10_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_13_10_2021_13_10_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_13_10_2021_13_10_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_14_10_2021_14_10_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_14_10_2021_14_10_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_15_10_2021_15_10_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_15_10_2021_15_10_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_16_10_2021_16_10_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_16_10_2021_16_10_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_17_10_2021_17_10_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_17_10_2021_17_10_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_18_10_2021_18_10_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_18_10_2021_18_10_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_19_10_2021_19_10_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_19_10_2021_19_10_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_20_10_2021_20_10_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_20_10_2021_20_10_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_21_10_2021_21_10_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_21_10_2021_21_10_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_22_10_2021_22_10_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_22_10_2021_22_10_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_23_10_2021_23_10_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_23_10_2021_23_10_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_24_10_2021_24_10_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_24_10_2021_24_10_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_25_10_2021_25_10_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_25_10_2021_25_10_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_26_10_2021_26_10_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_26_10_2021_26_10_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_27_10_2021_27_10_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_27_10_2021_27_10_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_28_10_2021_28_10_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_28_10_2021_28_10_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_29_10_2021_29_10_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_29_10_2021_29_10_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_30_10_2021_30_10_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_30_10_2021_30_10_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_31_10_2021_31_10_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_10/TXT/INT_PBC_EV_H_1_31_10_2021_31_10_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_01_11_2021_01_11_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_01_11_2021_01_11_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_02_11_2021_02_11_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_02_11_2021_02_11_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_03_11_2021_03_11_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_03_11_2021_03_11_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_04_11_2021_04_11_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_04_11_2021_04_11_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_05_11_2021_05_11_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_05_11_2021_05_11_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_06_11_2021_06_11_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_06_11_2021_06_11_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_07_11_2021_07_11_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_07_11_2021_07_11_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_08_11_2021_08_11_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_08_11_2021_08_11_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_09_11_2021_09_11_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_09_11_2021_09_11_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_10_11_2021_10_11_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_10_11_2021_10_11_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_11_11_2021_11_11_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_11_11_2021_11_11_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_12_11_2021_12_11_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_12_11_2021_12_11_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_13_11_2021_13_11_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_13_11_2021_13_11_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_14_11_2021_14_11_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_14_11_2021_14_11_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_15_11_2021_15_11_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_15_11_2021_15_11_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_16_11_2021_16_11_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_16_11_2021_16_11_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_17_11_2021_17_11_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_17_11_2021_17_11_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_18_11_2021_18_11_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_18_11_2021_18_11_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_19_11_2021_19_11_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_19_11_2021_19_11_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_20_11_2021_20_11_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_20_11_2021_20_11_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_21_11_2021_21_11_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_21_11_2021_21_11_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_22_11_2021_22_11_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_22_11_2021_22_11_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_23_11_2021_23_11_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_23_11_2021_23_11_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_24_11_2021_24_11_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_24_11_2021_24_11_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_25_11_2021_25_11_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_25_11_2021_25_11_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_26_11_2021_26_11_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_26_11_2021_26_11_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_27_11_2021_27_11_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_27_11_2021_27_11_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_28_11_2021_28_11_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_28_11_2021_28_11_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_29_11_2021_29_11_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_29_11_2021_29_11_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_30_11_2021_30_11_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_11/TXT/INT_PBC_EV_H_1_30_11_2021_30_11_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_01_12_2021_01_12_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_01_12_2021_01_12_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_02_12_2021_02_12_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_02_12_2021_02_12_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_03_12_2021_03_12_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_03_12_2021_03_12_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_04_12_2021_04_12_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_04_12_2021_04_12_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_05_12_2021_05_12_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_05_12_2021_05_12_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_06_12_2021_06_12_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_06_12_2021_06_12_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_07_12_2021_07_12_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_07_12_2021_07_12_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_08_12_2021_08_12_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_08_12_2021_08_12_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_09_12_2021_09_12_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_09_12_2021_09_12_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_10_12_2021_10_12_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_10_12_2021_10_12_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_11_12_2021_11_12_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_11_12_2021_11_12_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_12_12_2021_12_12_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_12_12_2021_12_12_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_13_12_2021_13_12_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_13_12_2021_13_12_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_14_12_2021_14_12_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_14_12_2021_14_12_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_15_12_2021_15_12_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_15_12_2021_15_12_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_16_12_2021_16_12_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_16_12_2021_16_12_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_17_12_2021_17_12_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_17_12_2021_17_12_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_18_12_2021_18_12_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_18_12_2021_18_12_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_19_12_2021_19_12_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_19_12_2021_19_12_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_20_12_2021_20_12_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_20_12_2021_20_12_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_21_12_2021_21_12_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_21_12_2021_21_12_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_22_12_2021_22_12_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_22_12_2021_22_12_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_23_12_2021_23_12_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_23_12_2021_23_12_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_24_12_2021_24_12_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_24_12_2021_24_12_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_25_12_2021_25_12_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_25_12_2021_25_12_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_26_12_2021_26_12_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_26_12_2021_26_12_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_27_12_2021_27_12_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_27_12_2021_27_12_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_28_12_2021_28_12_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_28_12_2021_28_12_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_29_12_2021_29_12_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_29_12_2021_29_12_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_30_12_2021_30_12_2021.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_30_12_2021_30_12_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_31_12_2021_31_12_2021.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2021/MES_12/TXT/INT_PBC_EV_H_1_31_12_2021_31_12_2021.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_01_01_2022_01_01_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_01_01_2022_01_01_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_02_01_2022_02_01_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_02_01_2022_02_01_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_03_01_2022_03_01_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_03_01_2022_03_01_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_04_01_2022_04_01_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_04_01_2022_04_01_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_05_01_2022_05_01_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_05_01_2022_05_01_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_06_01_2022_06_01_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_06_01_2022_06_01_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_07_01_2022_07_01_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_07_01_2022_07_01_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_08_01_2022_08_01_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_08_01_2022_08_01_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_09_01_2022_09_01_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_09_01_2022_09_01_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_10_01_2022_10_01_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_10_01_2022_10_01_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_11_01_2022_11_01_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_11_01_2022_11_01_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_12_01_2022_12_01_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_12_01_2022_12_01_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_13_01_2022_13_01_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_13_01_2022_13_01_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_14_01_2022_14_01_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_14_01_2022_14_01_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_15_01_2022_15_01_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_15_01_2022_15_01_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_16_01_2022_16_01_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_16_01_2022_16_01_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_17_01_2022_17_01_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_17_01_2022_17_01_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_18_01_2022_18_01_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_18_01_2022_18_01_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_19_01_2022_19_01_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_19_01_2022_19_01_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_20_01_2022_20_01_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_20_01_2022_20_01_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_21_01_2022_21_01_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_21_01_2022_21_01_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_22_01_2022_22_01_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_22_01_2022_22_01_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_23_01_2022_23_01_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_23_01_2022_23_01_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_24_01_2022_24_01_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_24_01_2022_24_01_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_25_01_2022_25_01_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_25_01_2022_25_01_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_26_01_2022_26_01_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_26_01_2022_26_01_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_27_01_2022_27_01_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_27_01_2022_27_01_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_28_01_2022_28_01_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_28_01_2022_28_01_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_29_01_2022_29_01_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_29_01_2022_29_01_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_30_01_2022_30_01_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_30_01_2022_30_01_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_31_01_2022_31_01_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_01/TXT/INT_PBC_EV_H_1_31_01_2022_31_01_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_01_02_2022_01_02_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_01_02_2022_01_02_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_02_02_2022_02_02_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_02_02_2022_02_02_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_03_02_2022_03_02_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_03_02_2022_03_02_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_04_02_2022_04_02_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_04_02_2022_04_02_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_05_02_2022_05_02_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_05_02_2022_05_02_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_06_02_2022_06_02_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_06_02_2022_06_02_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_07_02_2022_07_02_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_07_02_2022_07_02_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_08_02_2022_08_02_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_08_02_2022_08_02_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_09_02_2022_09_02_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_09_02_2022_09_02_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_10_02_2022_10_02_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_10_02_2022_10_02_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_11_02_2022_11_02_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_11_02_2022_11_02_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_12_02_2022_12_02_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_12_02_2022_12_02_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_13_02_2022_13_02_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_13_02_2022_13_02_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_14_02_2022_14_02_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_14_02_2022_14_02_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_15_02_2022_15_02_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_15_02_2022_15_02_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_16_02_2022_16_02_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_16_02_2022_16_02_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_17_02_2022_17_02_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_17_02_2022_17_02_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_18_02_2022_18_02_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_18_02_2022_18_02_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_19_02_2022_19_02_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_19_02_2022_19_02_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_20_02_2022_20_02_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_20_02_2022_20_02_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_21_02_2022_21_02_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_21_02_2022_21_02_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_22_02_2022_22_02_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_22_02_2022_22_02_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_23_02_2022_23_02_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_23_02_2022_23_02_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_24_02_2022_24_02_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_24_02_2022_24_02_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_25_02_2022_25_02_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_25_02_2022_25_02_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_26_02_2022_26_02_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_26_02_2022_26_02_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_27_02_2022_27_02_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_27_02_2022_27_02_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_28_02_2022_28_02_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_02/TXT/INT_PBC_EV_H_1_28_02_2022_28_02_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_01_03_2022_01_03_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_01_03_2022_01_03_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_02_03_2022_02_03_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_02_03_2022_02_03_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_03_03_2022_03_03_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_03_03_2022_03_03_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_04_03_2022_04_03_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_04_03_2022_04_03_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_05_03_2022_05_03_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_05_03_2022_05_03_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_06_03_2022_06_03_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_06_03_2022_06_03_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_07_03_2022_07_03_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_07_03_2022_07_03_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_08_03_2022_08_03_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_08_03_2022_08_03_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_09_03_2022_09_03_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_09_03_2022_09_03_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_10_03_2022_10_03_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_10_03_2022_10_03_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_11_03_2022_11_03_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_11_03_2022_11_03_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_12_03_2022_12_03_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_12_03_2022_12_03_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_13_03_2022_13_03_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_13_03_2022_13_03_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_14_03_2022_14_03_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_14_03_2022_14_03_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_15_03_2022_15_03_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_15_03_2022_15_03_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_16_03_2022_16_03_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_16_03_2022_16_03_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_17_03_2022_17_03_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_17_03_2022_17_03_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_18_03_2022_18_03_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_18_03_2022_18_03_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_19_03_2022_19_03_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_19_03_2022_19_03_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_20_03_2022_20_03_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_20_03_2022_20_03_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_21_03_2022_21_03_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_21_03_2022_21_03_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_22_03_2022_22_03_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_22_03_2022_22_03_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_23_03_2022_23_03_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_23_03_2022_23_03_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_24_03_2022_24_03_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_24_03_2022_24_03_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_25_03_2022_25_03_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_25_03_2022_25_03_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_26_03_2022_26_03_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_26_03_2022_26_03_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_27_03_2022_27_03_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_27_03_2022_27_03_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_28_03_2022_28_03_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_28_03_2022_28_03_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_29_03_2022_29_03_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_29_03_2022_29_03_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_30_03_2022_30_03_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_30_03_2022_30_03_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_31_03_2022_31_03_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_03/TXT/INT_PBC_EV_H_1_31_03_2022_31_03_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_01_04_2022_01_04_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_01_04_2022_01_04_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_02_04_2022_02_04_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_02_04_2022_02_04_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_03_04_2022_03_04_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_03_04_2022_03_04_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_04_04_2022_04_04_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_04_04_2022_04_04_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_05_04_2022_05_04_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_05_04_2022_05_04_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_06_04_2022_06_04_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_06_04_2022_06_04_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_07_04_2022_07_04_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_07_04_2022_07_04_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_08_04_2022_08_04_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_08_04_2022_08_04_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_09_04_2022_09_04_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_09_04_2022_09_04_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_10_04_2022_10_04_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_10_04_2022_10_04_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_11_04_2022_11_04_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_11_04_2022_11_04_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_12_04_2022_12_04_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_12_04_2022_12_04_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_13_04_2022_13_04_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_13_04_2022_13_04_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_14_04_2022_14_04_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_14_04_2022_14_04_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_15_04_2022_15_04_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_15_04_2022_15_04_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_16_04_2022_16_04_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_16_04_2022_16_04_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_17_04_2022_17_04_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_17_04_2022_17_04_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_18_04_2022_18_04_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_18_04_2022_18_04_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_19_04_2022_19_04_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_19_04_2022_19_04_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_20_04_2022_20_04_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_20_04_2022_20_04_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_21_04_2022_21_04_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_21_04_2022_21_04_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_22_04_2022_22_04_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_22_04_2022_22_04_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_23_04_2022_23_04_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_23_04_2022_23_04_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_24_04_2022_24_04_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_24_04_2022_24_04_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_25_04_2022_25_04_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_25_04_2022_25_04_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_26_04_2022_26_04_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_26_04_2022_26_04_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_27_04_2022_27_04_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_27_04_2022_27_04_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_28_04_2022_28_04_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_28_04_2022_28_04_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_29_04_2022_29_04_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_29_04_2022_29_04_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_30_04_2022_30_04_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_04/TXT/INT_PBC_EV_H_1_30_04_2022_30_04_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_01_05_2022_01_05_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_01_05_2022_01_05_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_02_05_2022_02_05_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_02_05_2022_02_05_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_03_05_2022_03_05_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_03_05_2022_03_05_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_04_05_2022_04_05_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_04_05_2022_04_05_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_05_05_2022_05_05_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_05_05_2022_05_05_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_06_05_2022_06_05_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_06_05_2022_06_05_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_07_05_2022_07_05_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_07_05_2022_07_05_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_08_05_2022_08_05_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_08_05_2022_08_05_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_09_05_2022_09_05_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_09_05_2022_09_05_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_10_05_2022_10_05_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_10_05_2022_10_05_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_11_05_2022_11_05_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_11_05_2022_11_05_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_12_05_2022_12_05_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_12_05_2022_12_05_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_13_05_2022_13_05_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_13_05_2022_13_05_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_14_05_2022_14_05_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_14_05_2022_14_05_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_15_05_2022_15_05_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_15_05_2022_15_05_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_16_05_2022_16_05_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_16_05_2022_16_05_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_17_05_2022_17_05_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_17_05_2022_17_05_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_18_05_2022_18_05_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_18_05_2022_18_05_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_19_05_2022_19_05_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_19_05_2022_19_05_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_20_05_2022_20_05_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_20_05_2022_20_05_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_21_05_2022_21_05_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_21_05_2022_21_05_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_22_05_2022_22_05_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_22_05_2022_22_05_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_23_05_2022_23_05_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_23_05_2022_23_05_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_24_05_2022_24_05_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_24_05_2022_24_05_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_25_05_2022_25_05_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_25_05_2022_25_05_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_26_05_2022_26_05_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_26_05_2022_26_05_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_27_05_2022_27_05_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_27_05_2022_27_05_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_28_05_2022_28_05_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_28_05_2022_28_05_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_29_05_2022_29_05_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_29_05_2022_29_05_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_30_05_2022_30_05_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_30_05_2022_30_05_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_31_05_2022_31_05_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_05/TXT/INT_PBC_EV_H_1_31_05_2022_31_05_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_01_06_2022_01_06_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_01_06_2022_01_06_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_02_06_2022_02_06_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_02_06_2022_02_06_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_03_06_2022_03_06_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_03_06_2022_03_06_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_04_06_2022_04_06_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_04_06_2022_04_06_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_05_06_2022_05_06_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_05_06_2022_05_06_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_06_06_2022_06_06_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_06_06_2022_06_06_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_07_06_2022_07_06_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_07_06_2022_07_06_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_08_06_2022_08_06_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_08_06_2022_08_06_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_09_06_2022_09_06_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_09_06_2022_09_06_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_10_06_2022_10_06_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_10_06_2022_10_06_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_11_06_2022_11_06_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_11_06_2022_11_06_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_12_06_2022_12_06_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_12_06_2022_12_06_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_13_06_2022_13_06_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_13_06_2022_13_06_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_14_06_2022_14_06_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_14_06_2022_14_06_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_15_06_2022_15_06_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_15_06_2022_15_06_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_16_06_2022_16_06_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_16_06_2022_16_06_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_17_06_2022_17_06_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_17_06_2022_17_06_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_18_06_2022_18_06_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_18_06_2022_18_06_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_19_06_2022_19_06_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_19_06_2022_19_06_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_20_06_2022_20_06_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_20_06_2022_20_06_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_21_06_2022_21_06_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_21_06_2022_21_06_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_22_06_2022_22_06_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_22_06_2022_22_06_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_23_06_2022_23_06_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_23_06_2022_23_06_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_24_06_2022_24_06_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_24_06_2022_24_06_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_25_06_2022_25_06_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_25_06_2022_25_06_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_26_06_2022_26_06_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_26_06_2022_26_06_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_27_06_2022_27_06_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_27_06_2022_27_06_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_28_06_2022_28_06_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_28_06_2022_28_06_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_29_06_2022_29_06_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_29_06_2022_29_06_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_30_06_2022_30_06_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_06/TXT/INT_PBC_EV_H_1_30_06_2022_30_06_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_01_07_2022_01_07_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_01_07_2022_01_07_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_02_07_2022_02_07_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_02_07_2022_02_07_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_03_07_2022_03_07_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_03_07_2022_03_07_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_04_07_2022_04_07_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_04_07_2022_04_07_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_05_07_2022_05_07_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_05_07_2022_05_07_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_06_07_2022_06_07_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_06_07_2022_06_07_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_07_07_2022_07_07_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_07_07_2022_07_07_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_08_07_2022_08_07_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_08_07_2022_08_07_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_09_07_2022_09_07_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_09_07_2022_09_07_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_10_07_2022_10_07_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_10_07_2022_10_07_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_11_07_2022_11_07_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_11_07_2022_11_07_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_12_07_2022_12_07_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_12_07_2022_12_07_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_13_07_2022_13_07_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_13_07_2022_13_07_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_14_07_2022_14_07_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_14_07_2022_14_07_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_15_07_2022_15_07_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_15_07_2022_15_07_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_16_07_2022_16_07_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_16_07_2022_16_07_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_17_07_2022_17_07_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_17_07_2022_17_07_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_18_07_2022_18_07_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_18_07_2022_18_07_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_19_07_2022_19_07_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_19_07_2022_19_07_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_20_07_2022_20_07_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_20_07_2022_20_07_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_21_07_2022_21_07_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_21_07_2022_21_07_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_22_07_2022_22_07_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_22_07_2022_22_07_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_23_07_2022_23_07_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_23_07_2022_23_07_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_24_07_2022_24_07_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_24_07_2022_24_07_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_25_07_2022_25_07_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_25_07_2022_25_07_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_26_07_2022_26_07_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_26_07_2022_26_07_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_27_07_2022_27_07_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_27_07_2022_27_07_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_28_07_2022_28_07_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_28_07_2022_28_07_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_29_07_2022_29_07_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_29_07_2022_29_07_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_30_07_2022_30_07_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_30_07_2022_30_07_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_31_07_2022_31_07_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_07/TXT/INT_PBC_EV_H_1_31_07_2022_31_07_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_01_08_2022_01_08_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_01_08_2022_01_08_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_02_08_2022_02_08_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_02_08_2022_02_08_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_03_08_2022_03_08_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_03_08_2022_03_08_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_04_08_2022_04_08_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_04_08_2022_04_08_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_05_08_2022_05_08_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_05_08_2022_05_08_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_06_08_2022_06_08_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_06_08_2022_06_08_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_07_08_2022_07_08_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_07_08_2022_07_08_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_08_08_2022_08_08_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_08_08_2022_08_08_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_09_08_2022_09_08_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_09_08_2022_09_08_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_10_08_2022_10_08_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_10_08_2022_10_08_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_11_08_2022_11_08_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_11_08_2022_11_08_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_12_08_2022_12_08_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_12_08_2022_12_08_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_13_08_2022_13_08_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_13_08_2022_13_08_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_14_08_2022_14_08_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_14_08_2022_14_08_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_15_08_2022_15_08_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_15_08_2022_15_08_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_16_08_2022_16_08_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_16_08_2022_16_08_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_17_08_2022_17_08_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_17_08_2022_17_08_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_18_08_2022_18_08_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_18_08_2022_18_08_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_19_08_2022_19_08_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_19_08_2022_19_08_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_20_08_2022_20_08_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_20_08_2022_20_08_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_21_08_2022_21_08_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_21_08_2022_21_08_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_22_08_2022_22_08_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_22_08_2022_22_08_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_23_08_2022_23_08_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_23_08_2022_23_08_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_24_08_2022_24_08_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_24_08_2022_24_08_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_25_08_2022_25_08_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_25_08_2022_25_08_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_26_08_2022_26_08_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_26_08_2022_26_08_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_27_08_2022_27_08_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_27_08_2022_27_08_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_28_08_2022_28_08_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_28_08_2022_28_08_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_29_08_2022_29_08_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_29_08_2022_29_08_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_30_08_2022_30_08_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_30_08_2022_30_08_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_31_08_2022_31_08_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_08/TXT/INT_PBC_EV_H_1_31_08_2022_31_08_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_01_09_2022_01_09_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_01_09_2022_01_09_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_02_09_2022_02_09_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_02_09_2022_02_09_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_03_09_2022_03_09_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_03_09_2022_03_09_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_04_09_2022_04_09_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_04_09_2022_04_09_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_05_09_2022_05_09_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_05_09_2022_05_09_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_06_09_2022_06_09_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_06_09_2022_06_09_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_07_09_2022_07_09_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_07_09_2022_07_09_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_08_09_2022_08_09_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_08_09_2022_08_09_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_09_09_2022_09_09_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_09_09_2022_09_09_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_10_09_2022_10_09_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_10_09_2022_10_09_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_11_09_2022_11_09_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_11_09_2022_11_09_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_12_09_2022_12_09_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_12_09_2022_12_09_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_13_09_2022_13_09_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_13_09_2022_13_09_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_14_09_2022_14_09_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_14_09_2022_14_09_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_15_09_2022_15_09_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_15_09_2022_15_09_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_16_09_2022_16_09_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_16_09_2022_16_09_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_17_09_2022_17_09_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_17_09_2022_17_09_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_18_09_2022_18_09_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_18_09_2022_18_09_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_19_09_2022_19_09_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_19_09_2022_19_09_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_20_09_2022_20_09_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_20_09_2022_20_09_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_21_09_2022_21_09_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_21_09_2022_21_09_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_22_09_2022_22_09_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_22_09_2022_22_09_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_23_09_2022_23_09_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_23_09_2022_23_09_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_24_09_2022_24_09_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_24_09_2022_24_09_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_25_09_2022_25_09_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_25_09_2022_25_09_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_26_09_2022_26_09_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_26_09_2022_26_09_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_27_09_2022_27_09_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_27_09_2022_27_09_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_28_09_2022_28_09_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_28_09_2022_28_09_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_29_09_2022_29_09_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_29_09_2022_29_09_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_30_09_2022_30_09_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_09/TXT/INT_PBC_EV_H_1_30_09_2022_30_09_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_01_10_2022_01_10_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_01_10_2022_01_10_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_02_10_2022_02_10_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_02_10_2022_02_10_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_03_10_2022_03_10_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_03_10_2022_03_10_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_04_10_2022_04_10_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_04_10_2022_04_10_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_05_10_2022_05_10_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_05_10_2022_05_10_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_06_10_2022_06_10_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_06_10_2022_06_10_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_07_10_2022_07_10_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_07_10_2022_07_10_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_08_10_2022_08_10_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_08_10_2022_08_10_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_09_10_2022_09_10_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_09_10_2022_09_10_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_10_10_2022_10_10_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_10_10_2022_10_10_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_11_10_2022_11_10_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_11_10_2022_11_10_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_12_10_2022_12_10_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_12_10_2022_12_10_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_13_10_2022_13_10_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_13_10_2022_13_10_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_14_10_2022_14_10_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_14_10_2022_14_10_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_15_10_2022_15_10_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_15_10_2022_15_10_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_16_10_2022_16_10_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_16_10_2022_16_10_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_17_10_2022_17_10_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_17_10_2022_17_10_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_18_10_2022_18_10_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_18_10_2022_18_10_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_19_10_2022_19_10_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_19_10_2022_19_10_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_20_10_2022_20_10_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_20_10_2022_20_10_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_21_10_2022_21_10_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_21_10_2022_21_10_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_22_10_2022_22_10_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_22_10_2022_22_10_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_23_10_2022_23_10_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_23_10_2022_23_10_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_24_10_2022_24_10_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_24_10_2022_24_10_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_25_10_2022_25_10_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_25_10_2022_25_10_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_26_10_2022_26_10_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_26_10_2022_26_10_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_27_10_2022_27_10_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_27_10_2022_27_10_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_28_10_2022_28_10_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_28_10_2022_28_10_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_29_10_2022_29_10_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_29_10_2022_29_10_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_30_10_2022_30_10_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_30_10_2022_30_10_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_31_10_2022_31_10_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_10/TXT/INT_PBC_EV_H_1_31_10_2022_31_10_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_01_11_2022_01_11_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_01_11_2022_01_11_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_02_11_2022_02_11_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_02_11_2022_02_11_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_03_11_2022_03_11_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_03_11_2022_03_11_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_04_11_2022_04_11_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_04_11_2022_04_11_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_05_11_2022_05_11_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_05_11_2022_05_11_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_06_11_2022_06_11_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_06_11_2022_06_11_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_07_11_2022_07_11_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_07_11_2022_07_11_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_08_11_2022_08_11_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_08_11_2022_08_11_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_09_11_2022_09_11_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_09_11_2022_09_11_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_10_11_2022_10_11_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_10_11_2022_10_11_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_11_11_2022_11_11_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_11_11_2022_11_11_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_12_11_2022_12_11_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_12_11_2022_12_11_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_13_11_2022_13_11_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_13_11_2022_13_11_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_14_11_2022_14_11_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_14_11_2022_14_11_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_15_11_2022_15_11_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_15_11_2022_15_11_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_16_11_2022_16_11_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_16_11_2022_16_11_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_17_11_2022_17_11_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_17_11_2022_17_11_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_18_11_2022_18_11_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_18_11_2022_18_11_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_19_11_2022_19_11_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_19_11_2022_19_11_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_20_11_2022_20_11_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_20_11_2022_20_11_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_21_11_2022_21_11_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_21_11_2022_21_11_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_22_11_2022_22_11_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_22_11_2022_22_11_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_23_11_2022_23_11_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_23_11_2022_23_11_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_24_11_2022_24_11_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_24_11_2022_24_11_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_25_11_2022_25_11_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_25_11_2022_25_11_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_26_11_2022_26_11_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_26_11_2022_26_11_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_27_11_2022_27_11_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_27_11_2022_27_11_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_28_11_2022_28_11_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_28_11_2022_28_11_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_29_11_2022_29_11_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_29_11_2022_29_11_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_30_11_2022_30_11_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_11/TXT/INT_PBC_EV_H_1_30_11_2022_30_11_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_01_12_2022_01_12_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_01_12_2022_01_12_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_02_12_2022_02_12_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_02_12_2022_02_12_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_03_12_2022_03_12_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_03_12_2022_03_12_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_04_12_2022_04_12_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_04_12_2022_04_12_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_05_12_2022_05_12_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_05_12_2022_05_12_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_06_12_2022_06_12_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_06_12_2022_06_12_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_07_12_2022_07_12_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_07_12_2022_07_12_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_08_12_2022_08_12_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_08_12_2022_08_12_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_09_12_2022_09_12_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_09_12_2022_09_12_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_10_12_2022_10_12_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_10_12_2022_10_12_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_11_12_2022_11_12_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_11_12_2022_11_12_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_12_12_2022_12_12_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_12_12_2022_12_12_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_13_12_2022_13_12_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_13_12_2022_13_12_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_14_12_2022_14_12_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_14_12_2022_14_12_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_15_12_2022_15_12_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_15_12_2022_15_12_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_16_12_2022_16_12_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_16_12_2022_16_12_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_17_12_2022_17_12_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_17_12_2022_17_12_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_18_12_2022_18_12_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_18_12_2022_18_12_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_19_12_2022_19_12_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_19_12_2022_19_12_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_20_12_2022_20_12_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_20_12_2022_20_12_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_21_12_2022_21_12_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_21_12_2022_21_12_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_22_12_2022_22_12_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_22_12_2022_22_12_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_23_12_2022_23_12_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_23_12_2022_23_12_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_24_12_2022_24_12_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_24_12_2022_24_12_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_25_12_2022_25_12_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_25_12_2022_25_12_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_26_12_2022_26_12_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_26_12_2022_26_12_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_27_12_2022_27_12_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_27_12_2022_27_12_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_28_12_2022_28_12_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_28_12_2022_28_12_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_29_12_2022_29_12_2022.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_29_12_2022_29_12_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_30_12_2022_30_12_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_30_12_2022_30_12_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_31_12_2022_31_12_2022.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2022/MES_12/TXT/INT_PBC_EV_H_1_31_12_2022_31_12_2022.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_01_01_2023_01_01_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_01_01_2023_01_01_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_02_01_2023_02_01_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_02_01_2023_02_01_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_03_01_2023_03_01_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_03_01_2023_03_01_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_04_01_2023_04_01_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_04_01_2023_04_01_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_05_01_2023_05_01_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_05_01_2023_05_01_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_06_01_2023_06_01_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_06_01_2023_06_01_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_07_01_2023_07_01_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_07_01_2023_07_01_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_08_01_2023_08_01_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_08_01_2023_08_01_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_09_01_2023_09_01_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_09_01_2023_09_01_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_10_01_2023_10_01_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_10_01_2023_10_01_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_11_01_2023_11_01_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_11_01_2023_11_01_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_12_01_2023_12_01_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_12_01_2023_12_01_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_13_01_2023_13_01_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_13_01_2023_13_01_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_14_01_2023_14_01_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_14_01_2023_14_01_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_15_01_2023_15_01_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_15_01_2023_15_01_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_16_01_2023_16_01_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_16_01_2023_16_01_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_17_01_2023_17_01_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_17_01_2023_17_01_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_18_01_2023_18_01_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_18_01_2023_18_01_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_19_01_2023_19_01_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_19_01_2023_19_01_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_20_01_2023_20_01_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_20_01_2023_20_01_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_21_01_2023_21_01_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_21_01_2023_21_01_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_22_01_2023_22_01_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_22_01_2023_22_01_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_23_01_2023_23_01_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_23_01_2023_23_01_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_24_01_2023_24_01_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_24_01_2023_24_01_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_25_01_2023_25_01_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_25_01_2023_25_01_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_26_01_2023_26_01_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_26_01_2023_26_01_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_27_01_2023_27_01_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_27_01_2023_27_01_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_28_01_2023_28_01_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_28_01_2023_28_01_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_29_01_2023_29_01_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_29_01_2023_29_01_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_30_01_2023_30_01_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_30_01_2023_30_01_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_31_01_2023_31_01_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_01/TXT/INT_PBC_EV_H_1_31_01_2023_31_01_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_01_02_2023_01_02_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_01_02_2023_01_02_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_02_02_2023_02_02_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_02_02_2023_02_02_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_03_02_2023_03_02_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_03_02_2023_03_02_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_04_02_2023_04_02_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_04_02_2023_04_02_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_05_02_2023_05_02_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_05_02_2023_05_02_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_06_02_2023_06_02_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_06_02_2023_06_02_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_07_02_2023_07_02_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_07_02_2023_07_02_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_08_02_2023_08_02_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_08_02_2023_08_02_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_09_02_2023_09_02_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_09_02_2023_09_02_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_10_02_2023_10_02_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_10_02_2023_10_02_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_11_02_2023_11_02_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_11_02_2023_11_02_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_12_02_2023_12_02_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_12_02_2023_12_02_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_13_02_2023_13_02_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_13_02_2023_13_02_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_14_02_2023_14_02_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_14_02_2023_14_02_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_15_02_2023_15_02_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_15_02_2023_15_02_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_16_02_2023_16_02_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_16_02_2023_16_02_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_17_02_2023_17_02_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_17_02_2023_17_02_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_18_02_2023_18_02_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_18_02_2023_18_02_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_19_02_2023_19_02_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_19_02_2023_19_02_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_20_02_2023_20_02_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_20_02_2023_20_02_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_21_02_2023_21_02_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_21_02_2023_21_02_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_22_02_2023_22_02_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_22_02_2023_22_02_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_23_02_2023_23_02_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_23_02_2023_23_02_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_24_02_2023_24_02_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_24_02_2023_24_02_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_25_02_2023_25_02_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_25_02_2023_25_02_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_26_02_2023_26_02_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_26_02_2023_26_02_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_27_02_2023_27_02_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_27_02_2023_27_02_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_28_02_2023_28_02_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_02/TXT/INT_PBC_EV_H_1_28_02_2023_28_02_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_01_03_2023_01_03_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_01_03_2023_01_03_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_02_03_2023_02_03_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_02_03_2023_02_03_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_03_03_2023_03_03_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_03_03_2023_03_03_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_04_03_2023_04_03_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_04_03_2023_04_03_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_05_03_2023_05_03_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_05_03_2023_05_03_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_06_03_2023_06_03_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_06_03_2023_06_03_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_07_03_2023_07_03_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_07_03_2023_07_03_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_08_03_2023_08_03_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_08_03_2023_08_03_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_09_03_2023_09_03_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_09_03_2023_09_03_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_10_03_2023_10_03_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_10_03_2023_10_03_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_11_03_2023_11_03_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_11_03_2023_11_03_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_12_03_2023_12_03_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_12_03_2023_12_03_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_13_03_2023_13_03_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_13_03_2023_13_03_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_14_03_2023_14_03_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_14_03_2023_14_03_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_15_03_2023_15_03_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_15_03_2023_15_03_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_16_03_2023_16_03_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_16_03_2023_16_03_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_17_03_2023_17_03_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_17_03_2023_17_03_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_18_03_2023_18_03_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_18_03_2023_18_03_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_19_03_2023_19_03_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_19_03_2023_19_03_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_20_03_2023_20_03_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_20_03_2023_20_03_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_21_03_2023_21_03_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_21_03_2023_21_03_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_22_03_2023_22_03_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_22_03_2023_22_03_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_23_03_2023_23_03_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_23_03_2023_23_03_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_24_03_2023_24_03_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_24_03_2023_24_03_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_25_03_2023_25_03_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_25_03_2023_25_03_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_26_03_2023_26_03_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_26_03_2023_26_03_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_27_03_2023_27_03_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_27_03_2023_27_03_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_28_03_2023_28_03_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_28_03_2023_28_03_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_29_03_2023_29_03_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_29_03_2023_29_03_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_30_03_2023_30_03_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_30_03_2023_30_03_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_31_03_2023_31_03_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_03/TXT/INT_PBC_EV_H_1_31_03_2023_31_03_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_01_04_2023_01_04_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_01_04_2023_01_04_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_02_04_2023_02_04_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_02_04_2023_02_04_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_03_04_2023_03_04_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_03_04_2023_03_04_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_04_04_2023_04_04_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_04_04_2023_04_04_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_05_04_2023_05_04_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_05_04_2023_05_04_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_06_04_2023_06_04_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_06_04_2023_06_04_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_07_04_2023_07_04_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_07_04_2023_07_04_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_08_04_2023_08_04_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_08_04_2023_08_04_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_09_04_2023_09_04_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_09_04_2023_09_04_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_10_04_2023_10_04_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_10_04_2023_10_04_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_11_04_2023_11_04_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_11_04_2023_11_04_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_12_04_2023_12_04_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_12_04_2023_12_04_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_13_04_2023_13_04_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_13_04_2023_13_04_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_14_04_2023_14_04_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_14_04_2023_14_04_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_15_04_2023_15_04_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_15_04_2023_15_04_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_16_04_2023_16_04_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_16_04_2023_16_04_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_17_04_2023_17_04_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_17_04_2023_17_04_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_18_04_2023_18_04_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_18_04_2023_18_04_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_19_04_2023_19_04_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_19_04_2023_19_04_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_20_04_2023_20_04_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_20_04_2023_20_04_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_21_04_2023_21_04_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_21_04_2023_21_04_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_22_04_2023_22_04_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_22_04_2023_22_04_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_23_04_2023_23_04_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_23_04_2023_23_04_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_24_04_2023_24_04_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_24_04_2023_24_04_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_25_04_2023_25_04_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_25_04_2023_25_04_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_26_04_2023_26_04_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_26_04_2023_26_04_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_27_04_2023_27_04_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_27_04_2023_27_04_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_28_04_2023_28_04_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_28_04_2023_28_04_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_29_04_2023_29_04_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_29_04_2023_29_04_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_30_04_2023_30_04_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_04/TXT/INT_PBC_EV_H_1_30_04_2023_30_04_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_01_05_2023_01_05_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_01_05_2023_01_05_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_02_05_2023_02_05_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_02_05_2023_02_05_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_03_05_2023_03_05_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_03_05_2023_03_05_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_04_05_2023_04_05_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_04_05_2023_04_05_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_05_05_2023_05_05_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_05_05_2023_05_05_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_06_05_2023_06_05_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_06_05_2023_06_05_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_07_05_2023_07_05_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_07_05_2023_07_05_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_08_05_2023_08_05_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_08_05_2023_08_05_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_09_05_2023_09_05_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_09_05_2023_09_05_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_10_05_2023_10_05_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_10_05_2023_10_05_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_11_05_2023_11_05_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_11_05_2023_11_05_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_12_05_2023_12_05_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_12_05_2023_12_05_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_13_05_2023_13_05_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_13_05_2023_13_05_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_14_05_2023_14_05_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_14_05_2023_14_05_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_15_05_2023_15_05_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_15_05_2023_15_05_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_16_05_2023_16_05_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_16_05_2023_16_05_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_17_05_2023_17_05_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_17_05_2023_17_05_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_18_05_2023_18_05_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_18_05_2023_18_05_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_19_05_2023_19_05_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_19_05_2023_19_05_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_20_05_2023_20_05_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_20_05_2023_20_05_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_21_05_2023_21_05_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_21_05_2023_21_05_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_22_05_2023_22_05_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_22_05_2023_22_05_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_23_05_2023_23_05_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_23_05_2023_23_05_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_24_05_2023_24_05_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_24_05_2023_24_05_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_25_05_2023_25_05_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_25_05_2023_25_05_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_26_05_2023_26_05_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_26_05_2023_26_05_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_27_05_2023_27_05_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_27_05_2023_27_05_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_28_05_2023_28_05_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_28_05_2023_28_05_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_29_05_2023_29_05_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_29_05_2023_29_05_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_30_05_2023_30_05_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_30_05_2023_30_05_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_31_05_2023_31_05_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_05/TXT/INT_PBC_EV_H_1_31_05_2023_31_05_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_01_06_2023_01_06_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_01_06_2023_01_06_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_02_06_2023_02_06_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_02_06_2023_02_06_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_03_06_2023_03_06_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_03_06_2023_03_06_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_04_06_2023_04_06_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_04_06_2023_04_06_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_05_06_2023_05_06_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_05_06_2023_05_06_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_06_06_2023_06_06_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_06_06_2023_06_06_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_07_06_2023_07_06_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_07_06_2023_07_06_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_08_06_2023_08_06_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_08_06_2023_08_06_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_09_06_2023_09_06_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_09_06_2023_09_06_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_10_06_2023_10_06_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_10_06_2023_10_06_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_11_06_2023_11_06_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_11_06_2023_11_06_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_12_06_2023_12_06_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_12_06_2023_12_06_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_13_06_2023_13_06_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_13_06_2023_13_06_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_14_06_2023_14_06_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_14_06_2023_14_06_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_15_06_2023_15_06_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_15_06_2023_15_06_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_16_06_2023_16_06_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_16_06_2023_16_06_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_17_06_2023_17_06_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_17_06_2023_17_06_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_18_06_2023_18_06_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_18_06_2023_18_06_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_19_06_2023_19_06_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_19_06_2023_19_06_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_20_06_2023_20_06_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_20_06_2023_20_06_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_21_06_2023_21_06_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_21_06_2023_21_06_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_22_06_2023_22_06_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_22_06_2023_22_06_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_23_06_2023_23_06_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_23_06_2023_23_06_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_24_06_2023_24_06_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_24_06_2023_24_06_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_25_06_2023_25_06_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_25_06_2023_25_06_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_26_06_2023_26_06_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_26_06_2023_26_06_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_27_06_2023_27_06_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_27_06_2023_27_06_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_28_06_2023_28_06_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_28_06_2023_28_06_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_29_06_2023_29_06_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_29_06_2023_29_06_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_30_06_2023_30_06_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_06/TXT/INT_PBC_EV_H_1_30_06_2023_30_06_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_01_07_2023_01_07_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_01_07_2023_01_07_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_02_07_2023_02_07_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_02_07_2023_02_07_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_03_07_2023_03_07_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_03_07_2023_03_07_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_04_07_2023_04_07_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_04_07_2023_04_07_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_05_07_2023_05_07_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_05_07_2023_05_07_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_06_07_2023_06_07_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_06_07_2023_06_07_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_07_07_2023_07_07_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_07_07_2023_07_07_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_08_07_2023_08_07_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_08_07_2023_08_07_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_09_07_2023_09_07_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_09_07_2023_09_07_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_10_07_2023_10_07_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_10_07_2023_10_07_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_11_07_2023_11_07_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_11_07_2023_11_07_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_12_07_2023_12_07_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_12_07_2023_12_07_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_13_07_2023_13_07_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_13_07_2023_13_07_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_14_07_2023_14_07_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_14_07_2023_14_07_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_15_07_2023_15_07_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_15_07_2023_15_07_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_16_07_2023_16_07_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_16_07_2023_16_07_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_17_07_2023_17_07_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_17_07_2023_17_07_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_18_07_2023_18_07_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_18_07_2023_18_07_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_19_07_2023_19_07_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_19_07_2023_19_07_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_20_07_2023_20_07_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_20_07_2023_20_07_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_21_07_2023_21_07_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_21_07_2023_21_07_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_22_07_2023_22_07_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_22_07_2023_22_07_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_23_07_2023_23_07_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_23_07_2023_23_07_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_24_07_2023_24_07_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_24_07_2023_24_07_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_25_07_2023_25_07_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_25_07_2023_25_07_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_26_07_2023_26_07_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_26_07_2023_26_07_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_27_07_2023_27_07_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_27_07_2023_27_07_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_28_07_2023_28_07_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_28_07_2023_28_07_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_29_07_2023_29_07_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_29_07_2023_29_07_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_30_07_2023_30_07_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_30_07_2023_30_07_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_31_07_2023_31_07_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_07/TXT/INT_PBC_EV_H_1_31_07_2023_31_07_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_01_08_2023_01_08_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_01_08_2023_01_08_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_02_08_2023_02_08_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_02_08_2023_02_08_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_03_08_2023_03_08_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_03_08_2023_03_08_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_04_08_2023_04_08_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_04_08_2023_04_08_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_05_08_2023_05_08_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_05_08_2023_05_08_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_06_08_2023_06_08_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_06_08_2023_06_08_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_07_08_2023_07_08_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_07_08_2023_07_08_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_08_08_2023_08_08_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_08_08_2023_08_08_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_09_08_2023_09_08_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_09_08_2023_09_08_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_10_08_2023_10_08_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_10_08_2023_10_08_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_11_08_2023_11_08_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_11_08_2023_11_08_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_12_08_2023_12_08_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_12_08_2023_12_08_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_13_08_2023_13_08_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_13_08_2023_13_08_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_14_08_2023_14_08_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_14_08_2023_14_08_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_15_08_2023_15_08_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_15_08_2023_15_08_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_16_08_2023_16_08_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_16_08_2023_16_08_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_17_08_2023_17_08_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_17_08_2023_17_08_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_18_08_2023_18_08_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_18_08_2023_18_08_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_19_08_2023_19_08_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_19_08_2023_19_08_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_20_08_2023_20_08_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_20_08_2023_20_08_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_21_08_2023_21_08_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_21_08_2023_21_08_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_22_08_2023_22_08_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_22_08_2023_22_08_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_23_08_2023_23_08_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_23_08_2023_23_08_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_24_08_2023_24_08_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_24_08_2023_24_08_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_25_08_2023_25_08_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_25_08_2023_25_08_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_26_08_2023_26_08_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_26_08_2023_26_08_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_27_08_2023_27_08_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_27_08_2023_27_08_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_28_08_2023_28_08_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_28_08_2023_28_08_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_29_08_2023_29_08_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_29_08_2023_29_08_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_30_08_2023_30_08_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_30_08_2023_30_08_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_31_08_2023_31_08_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_08/TXT/INT_PBC_EV_H_1_31_08_2023_31_08_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_01_09_2023_01_09_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_01_09_2023_01_09_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_02_09_2023_02_09_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_02_09_2023_02_09_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_03_09_2023_03_09_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_03_09_2023_03_09_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_04_09_2023_04_09_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_04_09_2023_04_09_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_05_09_2023_05_09_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_05_09_2023_05_09_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_06_09_2023_06_09_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_06_09_2023_06_09_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_07_09_2023_07_09_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_07_09_2023_07_09_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_08_09_2023_08_09_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_08_09_2023_08_09_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_09_09_2023_09_09_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_09_09_2023_09_09_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_10_09_2023_10_09_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_10_09_2023_10_09_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_11_09_2023_11_09_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_11_09_2023_11_09_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_12_09_2023_12_09_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_12_09_2023_12_09_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_13_09_2023_13_09_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_13_09_2023_13_09_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_14_09_2023_14_09_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_14_09_2023_14_09_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_15_09_2023_15_09_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_15_09_2023_15_09_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_16_09_2023_16_09_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_16_09_2023_16_09_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_17_09_2023_17_09_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_17_09_2023_17_09_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_18_09_2023_18_09_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_18_09_2023_18_09_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_19_09_2023_19_09_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_19_09_2023_19_09_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_20_09_2023_20_09_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_20_09_2023_20_09_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_21_09_2023_21_09_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_21_09_2023_21_09_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_22_09_2023_22_09_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_22_09_2023_22_09_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_23_09_2023_23_09_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_23_09_2023_23_09_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_24_09_2023_24_09_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_24_09_2023_24_09_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_25_09_2023_25_09_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_25_09_2023_25_09_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_26_09_2023_26_09_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_26_09_2023_26_09_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_27_09_2023_27_09_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_27_09_2023_27_09_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_28_09_2023_28_09_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_28_09_2023_28_09_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_29_09_2023_29_09_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_29_09_2023_29_09_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_30_09_2023_30_09_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_09/TXT/INT_PBC_EV_H_1_30_09_2023_30_09_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_01_10_2023_01_10_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_01_10_2023_01_10_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_02_10_2023_02_10_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_02_10_2023_02_10_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_03_10_2023_03_10_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_03_10_2023_03_10_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_04_10_2023_04_10_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_04_10_2023_04_10_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_05_10_2023_05_10_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_05_10_2023_05_10_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_06_10_2023_06_10_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_06_10_2023_06_10_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_07_10_2023_07_10_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_07_10_2023_07_10_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_08_10_2023_08_10_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_08_10_2023_08_10_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_09_10_2023_09_10_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_09_10_2023_09_10_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_10_10_2023_10_10_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_10_10_2023_10_10_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_11_10_2023_11_10_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_11_10_2023_11_10_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_12_10_2023_12_10_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_12_10_2023_12_10_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_13_10_2023_13_10_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_13_10_2023_13_10_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_14_10_2023_14_10_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_14_10_2023_14_10_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_15_10_2023_15_10_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_15_10_2023_15_10_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_16_10_2023_16_10_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_16_10_2023_16_10_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_17_10_2023_17_10_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_17_10_2023_17_10_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_18_10_2023_18_10_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_18_10_2023_18_10_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_19_10_2023_19_10_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_19_10_2023_19_10_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_20_10_2023_20_10_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_20_10_2023_20_10_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_21_10_2023_21_10_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_21_10_2023_21_10_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_22_10_2023_22_10_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_22_10_2023_22_10_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_23_10_2023_23_10_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_23_10_2023_23_10_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_24_10_2023_24_10_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_24_10_2023_24_10_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_25_10_2023_25_10_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_25_10_2023_25_10_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_26_10_2023_26_10_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_26_10_2023_26_10_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_27_10_2023_27_10_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_27_10_2023_27_10_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_28_10_2023_28_10_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_28_10_2023_28_10_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_29_10_2023_29_10_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_29_10_2023_29_10_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_30_10_2023_30_10_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_30_10_2023_30_10_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_31_10_2023_31_10_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_10/TXT/INT_PBC_EV_H_1_31_10_2023_31_10_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_01_11_2023_01_11_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_01_11_2023_01_11_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_02_11_2023_02_11_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_02_11_2023_02_11_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_03_11_2023_03_11_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_03_11_2023_03_11_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_04_11_2023_04_11_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_04_11_2023_04_11_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_05_11_2023_05_11_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_05_11_2023_05_11_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_06_11_2023_06_11_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_06_11_2023_06_11_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_07_11_2023_07_11_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_07_11_2023_07_11_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_08_11_2023_08_11_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_08_11_2023_08_11_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_09_11_2023_09_11_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_09_11_2023_09_11_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_10_11_2023_10_11_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_10_11_2023_10_11_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_11_11_2023_11_11_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_11_11_2023_11_11_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_12_11_2023_12_11_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_12_11_2023_12_11_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_13_11_2023_13_11_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_13_11_2023_13_11_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_14_11_2023_14_11_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_14_11_2023_14_11_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_15_11_2023_15_11_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_15_11_2023_15_11_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_16_11_2023_16_11_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_16_11_2023_16_11_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_17_11_2023_17_11_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_17_11_2023_17_11_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_18_11_2023_18_11_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_18_11_2023_18_11_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_19_11_2023_19_11_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_19_11_2023_19_11_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_20_11_2023_20_11_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_20_11_2023_20_11_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_21_11_2023_21_11_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_21_11_2023_21_11_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_22_11_2023_22_11_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_22_11_2023_22_11_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_23_11_2023_23_11_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_23_11_2023_23_11_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_24_11_2023_24_11_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_24_11_2023_24_11_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_25_11_2023_25_11_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_25_11_2023_25_11_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_26_11_2023_26_11_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_26_11_2023_26_11_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_27_11_2023_27_11_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_27_11_2023_27_11_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_28_11_2023_28_11_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_28_11_2023_28_11_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_29_11_2023_29_11_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_29_11_2023_29_11_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_30_11_2023_30_11_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_11/TXT/INT_PBC_EV_H_1_30_11_2023_30_11_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_01_12_2023_01_12_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_01_12_2023_01_12_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_02_12_2023_02_12_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_02_12_2023_02_12_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_03_12_2023_03_12_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_03_12_2023_03_12_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_04_12_2023_04_12_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_04_12_2023_04_12_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_05_12_2023_05_12_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_05_12_2023_05_12_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_06_12_2023_06_12_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_06_12_2023_06_12_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_07_12_2023_07_12_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_07_12_2023_07_12_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_08_12_2023_08_12_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_08_12_2023_08_12_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_09_12_2023_09_12_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_09_12_2023_09_12_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_10_12_2023_10_12_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_10_12_2023_10_12_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_11_12_2023_11_12_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_11_12_2023_11_12_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_12_12_2023_12_12_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_12_12_2023_12_12_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_13_12_2023_13_12_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_13_12_2023_13_12_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_14_12_2023_14_12_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_14_12_2023_14_12_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_15_12_2023_15_12_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_15_12_2023_15_12_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_16_12_2023_16_12_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_16_12_2023_16_12_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_17_12_2023_17_12_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_17_12_2023_17_12_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_18_12_2023_18_12_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_18_12_2023_18_12_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_19_12_2023_19_12_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_19_12_2023_19_12_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_20_12_2023_20_12_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_20_12_2023_20_12_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_21_12_2023_21_12_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_21_12_2023_21_12_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_22_12_2023_22_12_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_22_12_2023_22_12_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_23_12_2023_23_12_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_23_12_2023_23_12_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_24_12_2023_24_12_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_24_12_2023_24_12_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_25_12_2023_25_12_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_25_12_2023_25_12_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_26_12_2023_26_12_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_26_12_2023_26_12_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_27_12_2023_27_12_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_27_12_2023_27_12_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_28_12_2023_28_12_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_28_12_2023_28_12_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_29_12_2023_29_12_2023.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_29_12_2023_29_12_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_30_12_2023_30_12_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_30_12_2023_30_12_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_31_12_2023_31_12_2023.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2023/MES_12/TXT/INT_PBC_EV_H_1_31_12_2023_31_12_2023.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_01_01_2024_01_01_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_01_01_2024_01_01_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_02_01_2024_02_01_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_02_01_2024_02_01_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_03_01_2024_03_01_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_03_01_2024_03_01_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_04_01_2024_04_01_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_04_01_2024_04_01_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_05_01_2024_05_01_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_05_01_2024_05_01_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_06_01_2024_06_01_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_06_01_2024_06_01_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_07_01_2024_07_01_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_07_01_2024_07_01_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_08_01_2024_08_01_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_08_01_2024_08_01_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_09_01_2024_09_01_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_09_01_2024_09_01_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_10_01_2024_10_01_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_10_01_2024_10_01_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_11_01_2024_11_01_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_11_01_2024_11_01_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_12_01_2024_12_01_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_12_01_2024_12_01_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_13_01_2024_13_01_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_13_01_2024_13_01_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_14_01_2024_14_01_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_14_01_2024_14_01_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_15_01_2024_15_01_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_15_01_2024_15_01_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_16_01_2024_16_01_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_16_01_2024_16_01_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_17_01_2024_17_01_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_17_01_2024_17_01_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_18_01_2024_18_01_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_18_01_2024_18_01_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_19_01_2024_19_01_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_19_01_2024_19_01_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_20_01_2024_20_01_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_20_01_2024_20_01_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_21_01_2024_21_01_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_21_01_2024_21_01_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_22_01_2024_22_01_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_22_01_2024_22_01_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_23_01_2024_23_01_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_23_01_2024_23_01_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_24_01_2024_24_01_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_24_01_2024_24_01_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_25_01_2024_25_01_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_25_01_2024_25_01_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_26_01_2024_26_01_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_26_01_2024_26_01_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_27_01_2024_27_01_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_27_01_2024_27_01_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_28_01_2024_28_01_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_28_01_2024_28_01_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_29_01_2024_29_01_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_29_01_2024_29_01_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_30_01_2024_30_01_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_30_01_2024_30_01_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_31_01_2024_31_01_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_01/TXT/INT_PBC_EV_H_1_31_01_2024_31_01_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_01_02_2024_01_02_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_01_02_2024_01_02_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_02_02_2024_02_02_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_02_02_2024_02_02_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_03_02_2024_03_02_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_03_02_2024_03_02_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_04_02_2024_04_02_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_04_02_2024_04_02_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_05_02_2024_05_02_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_05_02_2024_05_02_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_06_02_2024_06_02_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_06_02_2024_06_02_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_07_02_2024_07_02_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_07_02_2024_07_02_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_08_02_2024_08_02_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_08_02_2024_08_02_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_09_02_2024_09_02_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_09_02_2024_09_02_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_10_02_2024_10_02_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_10_02_2024_10_02_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_11_02_2024_11_02_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_11_02_2024_11_02_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_12_02_2024_12_02_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_12_02_2024_12_02_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_13_02_2024_13_02_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_13_02_2024_13_02_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_14_02_2024_14_02_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_14_02_2024_14_02_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_15_02_2024_15_02_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_15_02_2024_15_02_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_16_02_2024_16_02_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_16_02_2024_16_02_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_17_02_2024_17_02_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_17_02_2024_17_02_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_18_02_2024_18_02_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_18_02_2024_18_02_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_19_02_2024_19_02_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_19_02_2024_19_02_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_20_02_2024_20_02_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_20_02_2024_20_02_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_21_02_2024_21_02_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_21_02_2024_21_02_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_22_02_2024_22_02_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_22_02_2024_22_02_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_23_02_2024_23_02_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_23_02_2024_23_02_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_24_02_2024_24_02_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_24_02_2024_24_02_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_25_02_2024_25_02_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_25_02_2024_25_02_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_26_02_2024_26_02_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_26_02_2024_26_02_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_27_02_2024_27_02_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_27_02_2024_27_02_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_28_02_2024_28_02_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_28_02_2024_28_02_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_29_02_2024_29_02_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_02/TXT/INT_PBC_EV_H_1_29_02_2024_29_02_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_01_03_2024_01_03_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_01_03_2024_01_03_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_02_03_2024_02_03_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_02_03_2024_02_03_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_03_03_2024_03_03_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_03_03_2024_03_03_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_04_03_2024_04_03_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_04_03_2024_04_03_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_05_03_2024_05_03_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_05_03_2024_05_03_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_06_03_2024_06_03_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_06_03_2024_06_03_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_07_03_2024_07_03_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_07_03_2024_07_03_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_08_03_2024_08_03_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_08_03_2024_08_03_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_09_03_2024_09_03_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_09_03_2024_09_03_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_10_03_2024_10_03_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_10_03_2024_10_03_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_11_03_2024_11_03_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_11_03_2024_11_03_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_12_03_2024_12_03_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_12_03_2024_12_03_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_13_03_2024_13_03_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_13_03_2024_13_03_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_14_03_2024_14_03_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_14_03_2024_14_03_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_15_03_2024_15_03_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_15_03_2024_15_03_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_16_03_2024_16_03_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_16_03_2024_16_03_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_17_03_2024_17_03_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_17_03_2024_17_03_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_18_03_2024_18_03_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_18_03_2024_18_03_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_19_03_2024_19_03_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_19_03_2024_19_03_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_20_03_2024_20_03_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_20_03_2024_20_03_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_21_03_2024_21_03_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_21_03_2024_21_03_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_22_03_2024_22_03_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_22_03_2024_22_03_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_23_03_2024_23_03_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_23_03_2024_23_03_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_24_03_2024_24_03_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_24_03_2024_24_03_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_25_03_2024_25_03_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_25_03_2024_25_03_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_26_03_2024_26_03_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_26_03_2024_26_03_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_27_03_2024_27_03_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_27_03_2024_27_03_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_28_03_2024_28_03_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_28_03_2024_28_03_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_29_03_2024_29_03_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_29_03_2024_29_03_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_30_03_2024_30_03_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_30_03_2024_30_03_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_31_03_2024_31_03_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_03/TXT/INT_PBC_EV_H_1_31_03_2024_31_03_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_01_04_2024_01_04_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_01_04_2024_01_04_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_02_04_2024_02_04_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_02_04_2024_02_04_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_03_04_2024_03_04_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_03_04_2024_03_04_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_04_04_2024_04_04_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_04_04_2024_04_04_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_05_04_2024_05_04_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_05_04_2024_05_04_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_06_04_2024_06_04_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_06_04_2024_06_04_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_07_04_2024_07_04_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_07_04_2024_07_04_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_08_04_2024_08_04_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_08_04_2024_08_04_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_09_04_2024_09_04_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_09_04_2024_09_04_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_10_04_2024_10_04_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_10_04_2024_10_04_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_11_04_2024_11_04_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_11_04_2024_11_04_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_12_04_2024_12_04_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_12_04_2024_12_04_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_13_04_2024_13_04_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_13_04_2024_13_04_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_14_04_2024_14_04_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_14_04_2024_14_04_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_15_04_2024_15_04_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_15_04_2024_15_04_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_16_04_2024_16_04_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_16_04_2024_16_04_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_17_04_2024_17_04_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_17_04_2024_17_04_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_18_04_2024_18_04_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_18_04_2024_18_04_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_19_04_2024_19_04_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_19_04_2024_19_04_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_20_04_2024_20_04_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_20_04_2024_20_04_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_21_04_2024_21_04_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_21_04_2024_21_04_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_22_04_2024_22_04_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_22_04_2024_22_04_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_23_04_2024_23_04_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_23_04_2024_23_04_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_24_04_2024_24_04_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_24_04_2024_24_04_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_25_04_2024_25_04_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_25_04_2024_25_04_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_26_04_2024_26_04_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_26_04_2024_26_04_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_27_04_2024_27_04_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_27_04_2024_27_04_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_28_04_2024_28_04_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_28_04_2024_28_04_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_29_04_2024_29_04_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_29_04_2024_29_04_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_30_04_2024_30_04_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_04/TXT/INT_PBC_EV_H_1_30_04_2024_30_04_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_01_05_2024_01_05_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_01_05_2024_01_05_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_02_05_2024_02_05_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_02_05_2024_02_05_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_03_05_2024_03_05_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_03_05_2024_03_05_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_04_05_2024_04_05_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_04_05_2024_04_05_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_05_05_2024_05_05_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_05_05_2024_05_05_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_06_05_2024_06_05_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_06_05_2024_06_05_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_07_05_2024_07_05_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_07_05_2024_07_05_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_08_05_2024_08_05_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_08_05_2024_08_05_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_09_05_2024_09_05_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_09_05_2024_09_05_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_10_05_2024_10_05_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_10_05_2024_10_05_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_11_05_2024_11_05_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_11_05_2024_11_05_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_12_05_2024_12_05_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_12_05_2024_12_05_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_13_05_2024_13_05_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_13_05_2024_13_05_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_14_05_2024_14_05_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_14_05_2024_14_05_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_15_05_2024_15_05_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_15_05_2024_15_05_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_16_05_2024_16_05_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_16_05_2024_16_05_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_17_05_2024_17_05_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_17_05_2024_17_05_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_18_05_2024_18_05_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_18_05_2024_18_05_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_19_05_2024_19_05_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_19_05_2024_19_05_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_20_05_2024_20_05_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_20_05_2024_20_05_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_21_05_2024_21_05_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_21_05_2024_21_05_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_22_05_2024_22_05_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_22_05_2024_22_05_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_23_05_2024_23_05_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_23_05_2024_23_05_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_24_05_2024_24_05_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_24_05_2024_24_05_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_25_05_2024_25_05_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_25_05_2024_25_05_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_26_05_2024_26_05_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_26_05_2024_26_05_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_27_05_2024_27_05_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_27_05_2024_27_05_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_28_05_2024_28_05_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_28_05_2024_28_05_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_29_05_2024_29_05_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_29_05_2024_29_05_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_30_05_2024_30_05_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_30_05_2024_30_05_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_31_05_2024_31_05_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_05/TXT/INT_PBC_EV_H_1_31_05_2024_31_05_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_01_06_2024_01_06_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_01_06_2024_01_06_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_02_06_2024_02_06_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_02_06_2024_02_06_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_03_06_2024_03_06_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_03_06_2024_03_06_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_04_06_2024_04_06_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_04_06_2024_04_06_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_05_06_2024_05_06_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_05_06_2024_05_06_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_06_06_2024_06_06_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_06_06_2024_06_06_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_07_06_2024_07_06_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_07_06_2024_07_06_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_08_06_2024_08_06_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_08_06_2024_08_06_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_09_06_2024_09_06_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_09_06_2024_09_06_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_10_06_2024_10_06_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_10_06_2024_10_06_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_11_06_2024_11_06_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_11_06_2024_11_06_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_12_06_2024_12_06_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_12_06_2024_12_06_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_13_06_2024_13_06_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_13_06_2024_13_06_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_14_06_2024_14_06_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_14_06_2024_14_06_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_15_06_2024_15_06_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_15_06_2024_15_06_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_16_06_2024_16_06_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_16_06_2024_16_06_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_17_06_2024_17_06_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_17_06_2024_17_06_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_18_06_2024_18_06_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_18_06_2024_18_06_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_19_06_2024_19_06_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_19_06_2024_19_06_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_20_06_2024_20_06_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_20_06_2024_20_06_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_21_06_2024_21_06_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_21_06_2024_21_06_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_22_06_2024_22_06_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_22_06_2024_22_06_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_23_06_2024_23_06_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_23_06_2024_23_06_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_24_06_2024_24_06_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_24_06_2024_24_06_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_25_06_2024_25_06_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_25_06_2024_25_06_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_26_06_2024_26_06_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_26_06_2024_26_06_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_27_06_2024_27_06_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_27_06_2024_27_06_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_28_06_2024_28_06_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_28_06_2024_28_06_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_29_06_2024_29_06_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_29_06_2024_29_06_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_30_06_2024_30_06_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_06/TXT/INT_PBC_EV_H_1_30_06_2024_30_06_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_01_07_2024_01_07_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_01_07_2024_01_07_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_02_07_2024_02_07_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_02_07_2024_02_07_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_03_07_2024_03_07_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_03_07_2024_03_07_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_04_07_2024_04_07_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_04_07_2024_04_07_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_05_07_2024_05_07_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_05_07_2024_05_07_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_06_07_2024_06_07_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_06_07_2024_06_07_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_07_07_2024_07_07_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_07_07_2024_07_07_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_08_07_2024_08_07_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_08_07_2024_08_07_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_09_07_2024_09_07_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_09_07_2024_09_07_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_10_07_2024_10_07_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_10_07_2024_10_07_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_11_07_2024_11_07_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_11_07_2024_11_07_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_12_07_2024_12_07_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_12_07_2024_12_07_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_13_07_2024_13_07_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_13_07_2024_13_07_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_14_07_2024_14_07_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_14_07_2024_14_07_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_15_07_2024_15_07_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_15_07_2024_15_07_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_16_07_2024_16_07_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_16_07_2024_16_07_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_17_07_2024_17_07_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_17_07_2024_17_07_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_18_07_2024_18_07_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_18_07_2024_18_07_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_19_07_2024_19_07_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_19_07_2024_19_07_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_20_07_2024_20_07_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_20_07_2024_20_07_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_21_07_2024_21_07_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_21_07_2024_21_07_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_22_07_2024_22_07_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_22_07_2024_22_07_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_23_07_2024_23_07_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_23_07_2024_23_07_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_24_07_2024_24_07_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_24_07_2024_24_07_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_25_07_2024_25_07_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_25_07_2024_25_07_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_26_07_2024_26_07_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_26_07_2024_26_07_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_27_07_2024_27_07_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_27_07_2024_27_07_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_28_07_2024_28_07_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_28_07_2024_28_07_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_29_07_2024_29_07_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_29_07_2024_29_07_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_30_07_2024_30_07_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_30_07_2024_30_07_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_31_07_2024_31_07_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_07/TXT/INT_PBC_EV_H_1_31_07_2024_31_07_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_01_08_2024_01_08_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_01_08_2024_01_08_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_02_08_2024_02_08_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_02_08_2024_02_08_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_03_08_2024_03_08_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_03_08_2024_03_08_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_04_08_2024_04_08_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_04_08_2024_04_08_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_05_08_2024_05_08_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_05_08_2024_05_08_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_06_08_2024_06_08_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_06_08_2024_06_08_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_07_08_2024_07_08_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_07_08_2024_07_08_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_08_08_2024_08_08_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_08_08_2024_08_08_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_09_08_2024_09_08_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_09_08_2024_09_08_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_10_08_2024_10_08_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_10_08_2024_10_08_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_11_08_2024_11_08_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_11_08_2024_11_08_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_12_08_2024_12_08_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_12_08_2024_12_08_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_13_08_2024_13_08_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_13_08_2024_13_08_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_14_08_2024_14_08_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_14_08_2024_14_08_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_15_08_2024_15_08_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_15_08_2024_15_08_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_16_08_2024_16_08_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_16_08_2024_16_08_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_17_08_2024_17_08_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_17_08_2024_17_08_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_18_08_2024_18_08_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_18_08_2024_18_08_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_19_08_2024_19_08_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_19_08_2024_19_08_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_20_08_2024_20_08_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_20_08_2024_20_08_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_21_08_2024_21_08_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_21_08_2024_21_08_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_22_08_2024_22_08_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_22_08_2024_22_08_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_23_08_2024_23_08_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_23_08_2024_23_08_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_24_08_2024_24_08_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_24_08_2024_24_08_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_25_08_2024_25_08_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_25_08_2024_25_08_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_26_08_2024_26_08_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_26_08_2024_26_08_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_27_08_2024_27_08_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_27_08_2024_27_08_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_28_08_2024_28_08_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_28_08_2024_28_08_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_29_08_2024_29_08_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_29_08_2024_29_08_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_30_08_2024_30_08_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_30_08_2024_30_08_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_31_08_2024_31_08_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_08/TXT/INT_PBC_EV_H_1_31_08_2024_31_08_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_01_09_2024_01_09_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_01_09_2024_01_09_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_02_09_2024_02_09_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_02_09_2024_02_09_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_03_09_2024_03_09_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_03_09_2024_03_09_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_04_09_2024_04_09_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_04_09_2024_04_09_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_05_09_2024_05_09_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_05_09_2024_05_09_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_06_09_2024_06_09_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_06_09_2024_06_09_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_07_09_2024_07_09_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_07_09_2024_07_09_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_08_09_2024_08_09_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_08_09_2024_08_09_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_09_09_2024_09_09_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_09_09_2024_09_09_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_10_09_2024_10_09_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_10_09_2024_10_09_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_11_09_2024_11_09_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_11_09_2024_11_09_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_12_09_2024_12_09_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_12_09_2024_12_09_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_13_09_2024_13_09_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_13_09_2024_13_09_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_14_09_2024_14_09_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_14_09_2024_14_09_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_15_09_2024_15_09_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_15_09_2024_15_09_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_16_09_2024_16_09_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_16_09_2024_16_09_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_17_09_2024_17_09_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_17_09_2024_17_09_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_18_09_2024_18_09_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_18_09_2024_18_09_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_19_09_2024_19_09_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_19_09_2024_19_09_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_20_09_2024_20_09_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_20_09_2024_20_09_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_21_09_2024_21_09_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_21_09_2024_21_09_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_22_09_2024_22_09_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_22_09_2024_22_09_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_23_09_2024_23_09_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_23_09_2024_23_09_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_24_09_2024_24_09_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_24_09_2024_24_09_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_25_09_2024_25_09_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_25_09_2024_25_09_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_26_09_2024_26_09_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_26_09_2024_26_09_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_27_09_2024_27_09_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_27_09_2024_27_09_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_28_09_2024_28_09_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_28_09_2024_28_09_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_29_09_2024_29_09_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_29_09_2024_29_09_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_30_09_2024_30_09_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_09/TXT/INT_PBC_EV_H_1_30_09_2024_30_09_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_01_10_2024_01_10_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_01_10_2024_01_10_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_02_10_2024_02_10_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_02_10_2024_02_10_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_03_10_2024_03_10_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_03_10_2024_03_10_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_04_10_2024_04_10_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_04_10_2024_04_10_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_05_10_2024_05_10_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_05_10_2024_05_10_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_06_10_2024_06_10_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_06_10_2024_06_10_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_07_10_2024_07_10_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_07_10_2024_07_10_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_08_10_2024_08_10_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_08_10_2024_08_10_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_09_10_2024_09_10_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_09_10_2024_09_10_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_10_10_2024_10_10_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_10_10_2024_10_10_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_11_10_2024_11_10_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_11_10_2024_11_10_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_12_10_2024_12_10_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_12_10_2024_12_10_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_13_10_2024_13_10_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_13_10_2024_13_10_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_14_10_2024_14_10_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_14_10_2024_14_10_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_15_10_2024_15_10_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_15_10_2024_15_10_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_16_10_2024_16_10_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_16_10_2024_16_10_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_17_10_2024_17_10_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_17_10_2024_17_10_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_18_10_2024_18_10_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_18_10_2024_18_10_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_19_10_2024_19_10_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_19_10_2024_19_10_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_20_10_2024_20_10_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_20_10_2024_20_10_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_21_10_2024_21_10_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_21_10_2024_21_10_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_22_10_2024_22_10_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_22_10_2024_22_10_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_23_10_2024_23_10_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_23_10_2024_23_10_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_24_10_2024_24_10_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_24_10_2024_24_10_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_25_10_2024_25_10_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_25_10_2024_25_10_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_26_10_2024_26_10_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_26_10_2024_26_10_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_27_10_2024_27_10_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_27_10_2024_27_10_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_28_10_2024_28_10_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_28_10_2024_28_10_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_29_10_2024_29_10_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_29_10_2024_29_10_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_30_10_2024_30_10_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_30_10_2024_30_10_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_31_10_2024_31_10_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_10/TXT/INT_PBC_EV_H_1_31_10_2024_31_10_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_01_11_2024_01_11_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_01_11_2024_01_11_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_02_11_2024_02_11_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_02_11_2024_02_11_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_03_11_2024_03_11_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_03_11_2024_03_11_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_04_11_2024_04_11_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_04_11_2024_04_11_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_05_11_2024_05_11_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_05_11_2024_05_11_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_06_11_2024_06_11_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_06_11_2024_06_11_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_07_11_2024_07_11_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_07_11_2024_07_11_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_08_11_2024_08_11_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_08_11_2024_08_11_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_09_11_2024_09_11_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_09_11_2024_09_11_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_10_11_2024_10_11_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_10_11_2024_10_11_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_11_11_2024_11_11_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_11_11_2024_11_11_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_12_11_2024_12_11_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_12_11_2024_12_11_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_13_11_2024_13_11_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_13_11_2024_13_11_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_14_11_2024_14_11_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_14_11_2024_14_11_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_15_11_2024_15_11_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_15_11_2024_15_11_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_16_11_2024_16_11_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_16_11_2024_16_11_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_17_11_2024_17_11_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_17_11_2024_17_11_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_18_11_2024_18_11_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_18_11_2024_18_11_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_19_11_2024_19_11_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_19_11_2024_19_11_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_20_11_2024_20_11_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_20_11_2024_20_11_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_21_11_2024_21_11_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_21_11_2024_21_11_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_22_11_2024_22_11_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_22_11_2024_22_11_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_23_11_2024_23_11_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_23_11_2024_23_11_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_24_11_2024_24_11_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_24_11_2024_24_11_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_25_11_2024_25_11_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_25_11_2024_25_11_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_26_11_2024_26_11_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_26_11_2024_26_11_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_27_11_2024_27_11_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_27_11_2024_27_11_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_28_11_2024_28_11_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_28_11_2024_28_11_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_29_11_2024_29_11_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_29_11_2024_29_11_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_30_11_2024_30_11_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_11/TXT/INT_PBC_EV_H_1_30_11_2024_30_11_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_01_12_2024_01_12_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_01_12_2024_01_12_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_02_12_2024_02_12_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_02_12_2024_02_12_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_03_12_2024_03_12_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_03_12_2024_03_12_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_04_12_2024_04_12_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_04_12_2024_04_12_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_05_12_2024_05_12_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_05_12_2024_05_12_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_06_12_2024_06_12_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_06_12_2024_06_12_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_07_12_2024_07_12_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_07_12_2024_07_12_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_08_12_2024_08_12_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_08_12_2024_08_12_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_09_12_2024_09_12_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_09_12_2024_09_12_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_10_12_2024_10_12_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_10_12_2024_10_12_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_11_12_2024_11_12_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_11_12_2024_11_12_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_12_12_2024_12_12_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_12_12_2024_12_12_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_13_12_2024_13_12_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_13_12_2024_13_12_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_14_12_2024_14_12_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_14_12_2024_14_12_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_15_12_2024_15_12_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_15_12_2024_15_12_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_16_12_2024_16_12_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_16_12_2024_16_12_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_17_12_2024_17_12_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_17_12_2024_17_12_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_18_12_2024_18_12_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_18_12_2024_18_12_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_19_12_2024_19_12_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_19_12_2024_19_12_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_20_12_2024_20_12_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_20_12_2024_20_12_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_21_12_2024_21_12_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_21_12_2024_21_12_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_22_12_2024_22_12_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_22_12_2024_22_12_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_23_12_2024_23_12_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_23_12_2024_23_12_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_24_12_2024_24_12_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_24_12_2024_24_12_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_25_12_2024_25_12_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_25_12_2024_25_12_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_26_12_2024_26_12_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_26_12_2024_26_12_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_27_12_2024_27_12_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_27_12_2024_27_12_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_28_12_2024_28_12_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_28_12_2024_28_12_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_29_12_2024_29_12_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)
c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_29_12_2024_29_12_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_30_12_2024_30_12_2024.TXT ...
Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_30_12_2024_30_12_2024.TXT successfully processed
Requesting https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_31_12_2024_31_12_2024.TXT ...

c:\Users\marco\anaconda3\Lib\site-packages\OMIEData\FileReaders\marginal_price_file_reader.py:80: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  res = pd.concat([res, pd.DataFrame([dico])], ignore_index=True)

Url: https://www.omie.es/sites/default/files/dados/AGNO_2024/MES_12/TXT/INT_PBC_EV_H_1_31_12_2024_31_12_2024.TXT successfully processed
(8768, 27)
         DATE         CONCEPT        H1        H2        H3        H4  \
0  2019-01-01        PRICE_SP     66.88     66.88     66.00     63.64
1  2019-01-01        PRICE_PT     66.88     66.88     66.00     63.64
2  2019-01-01         ENER_IB  21044.90  19792.40  18724.40  17310.80
3  2019-01-01  ENER_IB_BILLAT  27635.00  26109.00  24569.20  23111.40
4  2019-01-02        PRICE_SP     61.74     53.00     48.23     47.23

         H5        H6       H7        H8  ...       H16       H17       H18  \
0     58.85     55.47     56.0     61.09  ...     60.84     61.09     63.08
1     58.85     55.47     56.0     61.09  ...     60.84     61.09     63.08
2  16687.70  16597.00  16741.7  17097.40  ...  21286.20  20656.00  20631.00
3  22372.80  22212.80  22377.5  22862.80  ...  27587.20  26956.70  27441.10
4     45.24     45.70     51.1     58.37  ...     60.69     62.19     67.10

        H19       H20       H21       H22       H23       H24  H25
0     66.66     67.06     67.26     68.07     67.08     64.03  NaN
1     66.66     67.06     67.26     68.07     67.08     64.03  NaN
2  22882.80  24256.20  25369.50  25674.60  25239.00  23188.80  NaN
3  29940.50  31429.20  32628.30  32792.50  32130.00  29870.70  NaN
4     69.30     69.25     68.07     68.01     66.66     64.28  NaN

[5 rows x 27 columns]

In [50]:
df_historic.head(10)

,DATE,CONCEPT,H1,H2,H3,H4,H5,H6,H7,H8,...,H16,H17,H18,H19,H20,H21,H22,H23,H24,H25
0,2019-01-01,PRICE_SP,66.88,66.88,66.00,63.64,58.85,55.47,56.00,61.09,...,60.84,61.09,63.08,66.66,67.06,67.26,68.07,67.08,64.03,NaN
1,2019-01-01,PRICE_PT,66.88,66.88,66.00,63.64,58.85,55.47,56.00,61.09,...,60.84,61.09,63.08,66.66,67.06,67.26,68.07,67.08,64.03,NaN
2,2019-01-01,ENER_IB,21044.90,19792.40,18724.40,17310.80,16687.70,16597.00,16741.70,17097.40,...,21286.20,20656.00,20631.00,22882.80,24256.20,25369.50,25674.60,25239.00,23188.80,NaN
3,2019-01-01,ENER_IB_BILLAT,27635.00,26109.00,24569.20,23111.40,22372.80,22212.80,22377.50,22862.80,...,27587.20,26956.70,27441.10,29940.50,31429.20,32628.30,32792.50,32130.00,29870.70,NaN
4,2019-01-02,PRICE_SP,61.74,53.00,48.23,47.23,45.24,45.70,51.10,58.37,...,60.69,62.19,67.10,69.30,69.25,68.07,68.01,66.66,64.28,NaN
5,2019-01-02,PRICE_PT,61.74,54.87,54.42,52.99,51.10,51.09,51.10,58.37,...,60.69,62.19,67.10,69.30,69.25,68.07,68.01,66.66,64.28,NaN
6,2019-01-02,ENER_IB,21440.90,20294.00,20495.50,20469.80,20998.80,21561.00,21207.00,23636.80,...,29347.70,28574.30,28094.20,29814.50,30833.20,31485.30,31465.40,30011.80,27043.40,NaN
7,2019-01-02,ENER_IB_BILLAT,27883.10,26234.00,26167.50,26018.00,26513.00,27264.50,27515.30,30424.20,...,36957.10,36123.00,35968.30,37849.20,38968.40,39729.90,39682.50,37867.50,34648.00,NaN
8,2019-01-03,PRICE_SP,62.01,54.85,52.19,50.21,50.20,52.19,54.91,66.58,...,68.01,68.99,70.00,71.10,70.55,68.38,67.83,66.10,66.88,NaN
9,2019-01-03,PRICE_PT,62.01,54.85,52.19,50.21,50.20,52.19,54.91,66.58,...,68.01,68.99,70.00,71.10,70.55,68.38,67.83,66.10,66.88,NaN

In [49]:
df_historic.shape

(8768, 27)

In [54]:
# Filtrar solo precio España
df_price = df_historic[df_historic["CONCEPT"] == "PRICE_SP"].copy()

# De formato ancho a largo
hour_cols = [f"H{i}" for i in range(1, 25)]
df_long = df_price.melt(
    id_vars=["DATE"],
    value_vars=hour_cols,
    var_name="hour",
    value_name="price_es"
)

# Convertir hora a número
df_long["hour"] = df_long["hour"].str.replace("H", "").astype(int)

# Ordenar
df_long = df_long.sort_values(["DATE", "hour"]).reset_index(drop=True)

print(df_long.shape)
print(df_long.head())

(52608, 3)
         DATE  hour  price_es
0  2019-01-01     1     66.88
1  2019-01-01     2     66.88
2  2019-01-01     3     66.00
3  2019-01-01     4     63.64
4  2019-01-01     5     58.85

In [55]:
print(df_long["DATE"].min())
print(df_long["DATE"].max())

2019-01-01
2024-12-31

In [56]:
df_long["DATE"] = pd.to_datetime(df_long["DATE"])
df_long["year"] = df_long["DATE"].dt.year
df_long["month"] = df_long["DATE"].dt.month
df_long["day"] = df_long["DATE"].dt.day
df_long["datetime"] = pd.to_datetime(df_long[["year", "month", "day"]].assign(hour=df_long["hour"] - 1))

# Renombrar DATE a date para consistencia
df_long = df_long.drop(columns="DATE")

print(df_long.shape)
print(df_long.head())

(52608, 6)
   hour  price_es  year  month  day            datetime
0     1     66.88  2019      1    1 2019-01-01 00:00:00
1     2     66.88  2019      1    1 2019-01-01 01:00:00
2     3     66.00  2019      1    1 2019-01-01 02:00:00
3     4     63.64  2019      1    1 2019-01-01 03:00:00
4     5     58.85  2019      1    1 2019-01-01 04:00:00

In [57]:
import sqlite3
import os

base_dir = os.path.abspath(os.path.join(os.getcwd(), ".."))
db_path = os.path.join(base_dir, "data", "electricity.db")
conn = sqlite3.connect(db_path)

df_long.to_sql("omie_prices_historic", conn, if_exists="replace", index=False)
print(f"Tabla creada con {len(df_long)} filas")

# Verificar
pd.read_sql("SELECT name FROM sqlite_master WHERE type='table'", conn)

Tabla creada con 52608 filas

                   name
0           omie_prices
1         omie_features
2  omie_prices_historic

In [58]:
# Guardemos los datos del historico
df_long.to_csv(os.path.join(base_dir, "data", "raw", "omie_historic_2019_2024.csv"), index=False)

In [ ]:
conn.close()

: